### ISSUE TITLE
s390x 运行脚本出错

### ISSUE THREAD

**Issue by Jacobax** [kirin10000/Xray-script#100]
错误提示：
获取CPU线程数失败！

没有其它内容，请问脚本是否在s390x架构无法运行？

**Comment by kirin10000** [comment]
你运行一下`cat /proc/cpuinfo`试试

**Comment by Jacobax** [comment]
> 你运行一下`cat /proc/cpuinfo`试试

![Screenshot_2022_0106_220945.png](https://user-images.githubusercontent.com/23228895/148395549-35ddf4fc-cc50-4593-8916-fbde2ec90476.png)

**Comment by kirin10000** [comment]
请试试更新后的脚本
