### ISSUE TITLE
已有cloudreve后，怎样安装合适？

### ISSUE THREAD

**Issue by Zoooooooooo** [kirin10000/Xray-script#101]
如题，已经部署过cloudreve，请问怎样修改您的脚本或者用什么方式进行其他项的安装？本人非深度开发者有点白 不好意思咨询一下。望指导一二~

**Comment by kirin10000** [comment]
脚本安装完成以后cloudreve安装在`/usr/local/cloudreve`，你可以在用脚本安装完之后去这里替换你的数据文件
