### ISSUE TITLE
XANMOD安装失败

### ISSUE THREAD

**Issue by HEXtoDEC** [kirin10000/Xray-script#103]
如题，XANMOD安装失败，报出来的错误是KEY添加错误。

然后我去了官网使用了官方的SHELL，也是同样的错误。但是我可以在大陆网络WGET到这个KEY，手工添加并完成了XANMOD的安装。

**Comment by kirin10000** [comment]
有log吗？

**Comment by HEXtoDEC** [comment]
> 有log吗？
```shell
wget -qO - https://dl.xanmod.org/gpg.key | sudo apt-key --keyring /etc/apt/trusted.gpg.d/xanmod-kernel.gpg add -
gpg: no valid OpenPGP data found.
```

**Comment by HEXtoDEC** [comment]
我手工，在本地 wget https://dl.xanmod.org/gpg.key 然后，再上传到服务器，最后添加进去是OK的

我在香港服务器上面去wget/curl都是不行的

我能确保服务器的DNS是OK的，使用的是8.8.8.8

**Comment by HEXtoDEC** [comment]
```shell
All packages are up to date.
W: Failed to fetch http://sg.mirrors.cloud.aliyuncs.com/ubuntu/dists/focal/InRelease  Could not resolve 'sg.mirrors.cloud.aliyuncs.com'
W: Failed to fetch http://sg.mirrors.cloud.aliyuncs.com/ubuntu/dists/focal-updates/InRelease  Could not resolve 'sg.mirrors.cloud.aliyuncs.com'
W: Failed to fetch http://sg.mirrors.cloud.aliyuncs.com/ubuntu/dists/focal-backports/InRelease  Could not resolve 'sg.mirrors.cloud.aliyuncs.com'
W: Failed to fetch http://sg.mirrors.cloud.aliyuncs.com/ubuntu/dists/focal-security/InRelease  Could not resolve 'sg.mirrors.cloud.aliyuncs.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1.2).
zlib1g-dev set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgd-dev : Depends: libxpm-dev but it is not going to be installed
             Depends: libx11-dev but it is not going to be installed
             Depends: libxt-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

去更换官方源了测试一下了

**Comment by kirin10000** [comment]
> 我手工，在本地 wget https://dl.xanmod.org/gpg.key 然后再上传到服务器，最后添加进去是OK的
> 
> 我在香港服务器上面去wget/curl都是不行的

说明不是脚本问题，是你的服务器无法连接xanmod服务器

**Comment by kirin10000** [comment]
> ```shell
> All packages are up to date.
> W: Failed to fetch http://sg.mirrors.cloud.aliyuncs.com/ubuntu/dists/focal/InRelease  Could not resolve 'sg.mirrors.cloud.aliyuncs.com'
> W: Failed to fetch http://sg.mirrors.cloud.aliyuncs.com/ubuntu/dists/focal-updates/InRelease  Could not resolve 'sg.mirrors.cloud.aliyuncs.com'
> W: Failed to fetch http://sg.mirrors.cloud.aliyuncs.com/ubuntu/dists/focal-backports/InRelease  Could not resolve 'sg.mirrors.cloud.aliyuncs.com'
> W: Failed to fetch http://sg.mirrors.cloud.aliyuncs.com/ubuntu/dists/focal-security/InRelease  Could not resolve 'sg.mirrors.cloud.aliyuncs.com'
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1.2).
> zlib1g-dev set to manually installed.
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  libgd-dev : Depends: libxpm-dev but it is not going to be installed
>              Depends: libx11-dev but it is not going to be installed
>              Depends: libxt-dev but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> ```
> 
> 去更换官方源了测试一下了

你换dns 之后需要更换apt源。这个apt源是阿里云本地的，`8.8.8.8`无法解析`sg.mirrors.cloud.aliyuncs.com`

**Comment by HEXtoDEC** [comment]
> > 我手工，在本地 wget https://dl.xanmod.org/gpg.key 然后再上传到服务器，最后添加进去是OK的
> > 我在香港服务器上面去wget/curl都是不行的
> 
> 说明不是脚本问题，是你的服务器无法连接xanmod服务器

我现在apt已经都是官方源了。
```shell
wget -qO - https://dl.xanmod.org/gpg.key | sudo apt-key --keyring /etc/apt/trusted.gpg.d/xanmod-kernel.gpg add -
cat: 'https://dl.xanmod.org/gpg.key': No such file or directory
```
这个官方指令还是会报错，可能我这有啥情况没查明，我这就手工吧。
