### ISSUE TITLE
VLESS-WebSocket-TLS安装问题

### ISSUE THREAD

**Issue by Helitec** [kirin10000/Xray-script#104]
如题，按照您的脚本部署后，VLESS-TCP-XTLS/TLS能用，VLESS-WebSocket-TLS始终用不上，参数也核对了几遍，日志始终显示 [Warning] [622670188] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://www.........): 301 Moved Permanently > websocket: bad handshake，请问这是Websocket协议安装出了问题吗？谢谢。

**Comment by kirin10000** [comment]
是否有使用cdn？如果使用了cloudflare，需要设置安全为严格

**Comment by Helitec** [comment]
> 是否有使用cdn？如果使用了cloudflare，需要设置安全为严格

您说的设置是在cloudfare里面设置吗？

**Comment by kirin10000** [comment]
> 需要打开域名进行初始化吗？还是说已经不用管了。

可以不管，如果你想用cloudreve网盘的话可以选择重装cloudreve
