### ISSUE TITLE
套Cloudflare的CDN无法连接，但套七牛CDN就可以连接

### ISSUE THREAD

**Issue by cxw620** [kirin10000/Xray-script#105]
如题。请求帮助。
使用TCP+gRPC+ws，添加了两个域名，一个备了案走国内CDN，一个没备案走cf。现在走七牛CDN的可以用，但cf的死活连接不上。详情如下：
套七牛的CDN的gRPC就能用了，速度还好，就是流量费挺贵。但ws不能用（七牛不支持）。
但是套cf的cdn就死活连接不上，已经设置SSL是严格，服务器也正确配置了证书，脚本没有报错。
尝试更换服务器上面的证书为cf自签证书，无效。
尝试修改nginx配置，无效，随后恢复默认了。
使用了自选ip。

客户端是v2rayn最新版，xray-core也是最新版。

以下为可能为解决问题提供帮助得到信息：
》》》------------------------------------------------------------------------------------------------------------------------------------
》》》grpc的日志：
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: remote error: tls: handshake failure"] > common/retry: all retry attempts failed
ws的日志：
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://***(域名)/clientdata):  > remote error: tls: handshake failure

》》》------------------------------------------------------------------------------------------------------------------------------------
》》》nginx的配置（保持默认没有改动,~为隐去域名等信息）：

server {
    listen 80 reuseport default_server;
    listen [::]:80 reuseport default_server;
    return 301 https://《domain1》;
}
server {
    listen 80;
    listen [::]:80;
    server_name 《domain1》 《domain2》;
    return 301 https://$host$request_uri;
}
server {
    listen unix:/dev/shm/nginx/default.sock default_server;
    listen unix:/dev/shm/nginx/h2.sock http2 default_server;
    return 301 https://《domain1》;
}
server {
    listen unix:/dev/shm/nginx/default.sock;
    listen unix:/dev/shm/nginx/h2.sock http2;
    server_name 《domain1》;
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
    #client_header_timeout 24h;
    #ignore_invalid_headers off;
    location = /《path》/TunMulti {
        client_max_body_size 0;
        client_body_timeout 24h;
        #keepalive_requests 1000;
        #keepalive_time 24h;
        keepalive_timeout 24h;
        send_timeout 24h;
        #grpc_buffer_size 0;
        grpc_read_timeout 24h;
        grpc_send_timeout 24h;
        #grpc_socket_keepalive off;
        lingering_close always;
        lingering_time 24h;
        lingering_timeout 24h;
        grpc_pass grpc://unix:/dev/shm/xray/grpc.sock;
    }
    location / {
        proxy_set_header X-Forwarded-For 127.0.0.1;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://unix:/dev/shm/cloudreve/cloudreve.sock;
        client_max_body_size 0;
    }
}
server {
    listen unix:/dev/shm/nginx/default.sock;
    listen unix:/dev/shm/nginx/h2.sock http2;
    server_name 《domain2》;
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
    #client_header_timeout 24h;
    #ignore_invalid_headers off;
    location = /《path》/TunMulti {
        client_max_body_size 0;
        client_body_timeout 24h;
        #keepalive_requests 1000;
        #keepalive_time 24h;
        keepalive_timeout 24h;
        send_timeout 24h;
        #grpc_buffer_size 0;
        grpc_read_timeout 24h;
        grpc_send_timeout 24h;
        #grpc_socket_keepalive off;
        lingering_close always;
        lingering_time 24h;
        lingering_timeout 24h;
        grpc_pass grpc://unix:/dev/shm/xray/grpc.sock;
    }
    location / {
        return 403;
    }
}
#-----------------不要修改以下内容----------------
#domain_list=《domain1》 《domain2》
#true_domain_list=《domain1》 《domain1》
#domain_config_list=2 2
#pretend_list=1 3

》》》----------------------------------------------------------------------------------------------------------
》》》xray的配置：

{
    "log": {
        "loglevel": "none"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "《id》",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "path": "/《path》",
                        "dest": "@/dev/shm/xray/ws.sock"
                    },
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/nginx/h2.sock"
                    },
                    {
                        "dest": "/dev/shm/nginx/default.sock"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/nginx/certs/《domain1》.cer",
                            "keyFile": "/usr/local/nginx/certs/《domain2》.key",
                            "ocspStapling": 3600
                        },
                        {
                            "certificateFile": "/usr/local/nginx/certs/《domain1》.cer",
                            "keyFile": "/usr/local/nginx/certs/《domain2》.key",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
        },
        {
            "listen": "/dev/shm/xray/grpc.sock",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "《id》"
                    }
                ]
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "《serviceName》"
                }
            }
        },
        {
            "listen": "@/dev/shm/xray/ws.sock",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "《id》"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/《path》"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

**Comment by kirin10000** [comment]
说明是cdn的问题，你看看cf有没有设置安全类型为严格

**Comment by cxw620** [comment]
> 

已经设置了，排查了好几遍，重新安装都用上了

**Comment by cxw620** [comment]
始终报告tls: handshake failure，grpc和ws都是tls错误

**Comment by kirin10000** [comment]
> 会不会是黑号了什么的

这我就不清楚了，你套上cf之后，直接用浏览器访问网页试试

**Comment by cxw620** [comment]
> > 会不会是黑号了什么的
> 
> 这我就不清楚了，你套上cf之后，直接用浏览器访问网页试试

直接访问是可以访问到的

**Comment by kirin10000** [comment]
有没有可能客户端配置错误，没有使用tls进行连接？
正常情况：
客户端<---ws+tls-->cdn<----ws+tls--->服务器

使用七牛云的时候：
客户端<---ws-->七牛云<----ws+tls--->服务器
这种情况cf可能就不行

你试试不使用cdn能否连接？

**Comment by kirin10000** [comment]
另外cloudflare里面有个选项，开启websocket和grpc的支持，需要打开

**Comment by cxw620** [comment]
> 

七牛云不支持ws, 走grpc, 正常使用快两周了.
直连是正常的, 速度不怎么样而已.
cloudflare的选项是打开的, 以前也在用. 就是用这个脚本搭建的就不能套cf. 我准备拿另外一台试一下别人的脚本看看行不行.
七牛好用是好用, 延迟几近CN2了, 只不过流量费也是节节高.
我给一下客户端的配置吧.
{
  "policy": {
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "log": {
    "access": "",
    "error": "",
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "0.0.0.0",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "udp": false,
        "allowTransparent": false
      }
    },
    {
      "tag": "api",
      "port": 12176,
      "listen": "127.0.0.1",
      "protocol": "dokodemo-door",
      "settings": {
        "udp": false,
        "address": "127.0.0.1",
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "(套cf的域名. 使用了自选ip)",
            "port": 443,
            "users": [
              {
                "id": "-----",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false
        },
        "wsSettings": {
          "path": "/8e174f0?ed=2048"
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "stats": {},
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "dns": {
    "hosts": {
      "proxy.golang.org": "142.250.176.17",
      "dns.google": "8.8.8.8"
    },
    "servers": [
      {
        "address": "192.168.192.198",
        "domains": [
          "domain:v2fly.org",
          "geosite:geolocation-!cn"
        ],
        "expectIPs": [
          "geoip:!cn"
        ]
      },
      "localhost"
    ],
    "disableCache": true,
    "disableFallback": true,
    "tag": "dns_inbound"
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "direct",
        "domain": [
          "geosite:tld-cn",
          "geosite:icloud",
          "geosite:category-games@cn",
          "geosite:cn",
          "geosite:private",
          "bilibili.com",
          "hdslb.com",
          "bilivideo.cn",
          "biliapi.com",
          "kaspersky-labs.com",
          "baidu.com",
          "bcebos.com",
          "bce-cdn.com",
          "baidupcs.com",
          "bdstatic.com",
          "doh.pub",
          "globalsign.net",
          "windows.com",
          "qq.com"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "direct",
        "ip": [
          "geoip:cn",
          "geoip:private",
          "223.5.5.5",
          "223.6.6.6",
          "114.114.114.114",
          "120.53.80.136",
          "1.117.168.62"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy",
        "enabled": true
      }
    ]
  }
}

**Comment by NP-Prob** [comment]
遇到了类似的问题，无法使用cloudflare，伪装网站也无法打开，会显示“The connection for this site is not secure”，直连ws-tls是可以通的。

**Comment by cxw620** [comment]
> @kirin10000 遇到了类似的问题，无法使用cloudflare，伪装网站也无法打开，会显示“The connection for this site is not secure”，直连ws-tls是可以通的。 如图1所示，在cloudflare的“边缘证书”页面可以看到证书处于“待验证（HTTP）”状态，要打开一个形如[http://xxxxx.xyz/.well-known/pki-validation/xxxxxxx.txt的链接验证，（我查了下，好像是要将后面的证书验证响应码填入网站根目录下的.well-known/pki-validation/xxxxxxx.txt内）](http://xxxxx.xyz/.well-known/pki-validation/xxxxxxx.txt%E7%9A%84%E9%93%BE%E6%8E%A5%E9%AA%8C%E8%AF%81%EF%BC%8C%EF%BC%88%E6%88%91%E6%9F%A5%E4%BA%86%E4%B8%8B%EF%BC%8C%E5%A5%BD%E5%83%8F%E6%98%AF%E8%A6%81%E5%B0%86%E5%90%8E%E9%9D%A2%E7%9A%84%E8%AF%81%E4%B9%A6%E9%AA%8C%E8%AF%81%E5%93%8D%E5%BA%94%E7%A0%81%E5%A1%AB%E5%85%A5%E7%BD%91%E7%AB%99%E6%A0%B9%E7%9B%AE%E5%BD%95%E4%B8%8B%E7%9A%84.well-known/pki-validation/xxxxxxx.txt%E5%86%85%EF%BC%89) 图2是nginx配置文件中nextcloud.conf的内容，看上去也有/.well-known/pki-validation文件夹，但robots.txt和/.well-known/pki-validation均无法访问。 ![1](https://user-images.githubusercontent.com/9911456/152162504-0ba0ca04-eb92-4feb-8136-dd102fa780c3.png) ![2](https://user-images.githubusercontent.com/9911456/152162522-65eb714c-28ee-412d-b10a-6bb6eb9eec40.png)

我觉得有道理!  我的也是这样提示要验证! 
域名满一年后需要续期SSL,似乎SSL证书最长有效期不能超过1年, 而cloudflare的证书说是长期有效但应该也是自动续期的, 有DNS验证和文件验证两种方法.

**Comment by NP-Prob** [comment]
> @kirin10000 遇到了类似的问题，无法使用cloudflare，伪装网站也无法打开，会显示“The connection for this site is not secure”，直连ws-tls是可以通的。 如图1所示，在cloudflare的“边缘证书”页面可以看到证书处于“待验证（HTTP）”状态，要打开一个形如[http://xxxxx.xyz/.well-known/pki-validation/xxxxxxx.txt 的链接验证，（我查了下，好像是要将后面的证书验证响应码填入网站根目录下的.well-known/pki-validation/xxxxxxx.txt内）](http://xxxxx.xyz/.well-known/pki-validation/xxxxxxx.txt%E7%9A%84%E9%93%BE%E6%8E%A5%E9%AA%8C%E8%AF%81%EF%BC%8C%EF%BC%88%E6%88%91%E6%9F%A5%E4%BA%86%E4%B8%8B%EF%BC%8C%E5%A5%BD%E5%83%8F%E6%98%AF%E8%A6%81%E5%B0%86%E5%90%8E%E9%9D%A2%E7%9A%84%E8%AF%81%E4%B9%A6%E9%AA%8C%E8%AF%81%E5%93%8D%E5%BA%94%E7%A0%81%E5%A1%AB%E5%85%A5%E7%BD%91%E7%AB%99%E6%A0%B9%E7%9B%AE%E5%BD%95%E4%B8%8B%E7%9A%84.well-known/pki-validation/xxxxxxx.txt%E5%86%85%EF%BC%89) 图2是nginx配置文件中nextcloud.conf的内容，看上去也有/.well-known/pki-validation文件夹，但robots.txt和/.well-known/pki-validation均无法访问。 ![1](https://user-images.githubusercontent.com/9911456/152172603-fbaf04de-a84b-4322-9795-77f4eeb91928.png) ![2](https://user-images.githubusercontent.com/9911456/152162522-65eb714c-28ee-412d-b10a-6bb6eb9eec40.png)

经摸索已解决，方法是，到如图1所示的cloudflare的“边缘证书界面”，按要求让浏览器访问http://xxxxx.xyz/.well-known/pki-validation/xxxxxxx.txt 地址可以获取 “证书验证响应”中的内容。
具体来说就是在vps里创建一个txt文件（比如在/usr/local/nginx/html文件夹下），内容写入“证书验证响应”中的内容，然后在xray.conf文件中加入一个字段如下图所示，这里location就是/.well-known/pki-validation/xxxxxxx.txt，然后block{ }里写入“alias 你的txt文件的路径”，就可以让cloudflare访问到这个文件进行验证了。
如果不成功，则点暗cloudflare对应网址的小云朵，再重新点亮，然后会重新生成一个“证书验证请求”和“证书验证响应”对，按上面的方法重新做一遍就好。
![image](https://user-images.githubusercontent.com/9911456/152176940-73fbbd18-6d90-484b-b42f-57513a10287e.png)

**Comment by cxw620** [comment]
> > @kirin10000 遇到了类似的问题，无法使用cloudflare，伪装网站也无法打开，会显示“The connection for this site is not secure”，直连ws-tls是可以通的。 如图1所示，在cloudflare的“边缘证书”页面可以看到证书处于“待验证（HTTP）”状态，要打开一个形如[http://xxxxx.xyz/.well-known/pki-validation/xxxxxxx.txt 的链接验证，（我查了下，好像是要将后面的证书验证响应码填入网站根目录下的.well-known/pki-validation/xxxxxxx.txt内）](http://xxxxx.xyz/.well-known/pki-validation/xxxxxxx.txt%E7%9A%84%E9%93%BE%E6%8E%A5%E9%AA%8C%E8%AF%81%EF%BC%8C%EF%BC%88%E6%88%91%E6%9F%A5%E4%BA%86%E4%B8%8B%EF%BC%8C%E5%A5%BD%E5%83%8F%E6%98%AF%E8%A6%81%E5%B0%86%E5%90%8E%E9%9D%A2%E7%9A%84%E8%AF%81%E4%B9%A6%E9%AA%8C%E8%AF%81%E5%93%8D%E5%BA%94%E7%A0%81%E5%A1%AB%E5%85%A5%E7%BD%91%E7%AB%99%E6%A0%B9%E7%9B%AE%E5%BD%95%E4%B8%8B%E7%9A%84.well-known/pki-validation/xxxxxxx.txt%E5%86%85%EF%BC%89) 图2是nginx配置文件中nextcloud.conf的内容，看上去也有/.well-known/pki-validation文件夹，但robots.txt和/.well-known/pki-validation均无法访问。 ![1](https://user-images.githubusercontent.com/9911456/152172603-fbaf04de-a84b-4322-9795-77f4eeb91928.png) ![2](https://user-images.githubusercontent.com/9911456/152162522-65eb714c-28ee-412d-b10a-6bb6eb9eec40.png)
> 
> 经摸索已解决，方法是，到如图1所示的cloudflare的“边缘证书界面”，按要求让浏览器访问http://xxxxx.xyz/.well-known/pki-validation/xxxxxxx.txt 地址可以获取 “证书验证响应”中的内容。 具体来说就是在vps里创建一个txt文件（比如在/usr/local/nginx/html文件夹下），内容写入“证书验证响应”中的内容，然后在xray.conf文件中加入一个字段如下图所示，这里location就是/.well-known/pki-validation/xxxxxxx.txt，然后block{ }里写入“alias 你的txt文件的路径”，就可以让cloudflare访问到这个文件进行验证了。 如果不成功，则点暗cloudflare对应网址的小云朵，再重新点亮，然后会重新生成一个“证书验证请求”和“证书验证响应”对，按上面的方法重新做一遍就好。 ![image](https://user-images.githubusercontent.com/9911456/152176940-73fbbd18-6d90-484b-b42f-57513a10287e.png)

好家伙, 马上试一下, 七牛的流量用得心滴血啊

**Comment by cxw620** [comment]
问题已解决.

**Comment by kirin10000** [comment]
> 经摸索已解决，方法是，

@NP-Prob cloudflare的证书是自动申请的，而且不需要服务器，不需要搭建网站。
你所描述的需要修改自己的网站配置才能获取到证书，我认为这是cloudflare自己的问题

**Comment by NP-Prob** [comment]
> 
> > 经摸索已解决，方法是，
> 
> @NP-Prob cloudflare的证书是自动申请的，而且不需要服务器，不需要搭建网站。
> 你所描述的需要修改自己的网站配置才能获取到证书，我认为这是cloudflare自己的问题
> 

确实应该是cloudflare新的证书验证方式的问题。脚本里添加处理原则上似乎可以，但非常麻烦，没有必要。不过可能会有后来人遇到类似问题，建议可以在安装脚本里添加一个本issue的链接，方便遇到问题的人自行处理。

**Comment by cxw620** [comment]
应该是如果DNS不是Cloudflare管理的, Cloudflare不能自动通过DNS更新其证书(好像现在正规证书强制不能超过1年有效期, 超过1年的都是自动续期的), 只能通过文件验证. 可以脚本添加个DNS请求获取伪装域名的NS, 如果不是cloudflare的就显示几句说明提醒该问题, 然后脚本可以设置入口自动化处理该问题, 应该就没什么问题了
