### ISSUE TITLE
cloudreve的管理员邮箱能否修改

### ISSUE THREAD

**Issue by golovo** [kirin10000/Xray-script#106]
感觉作者所写的脚本，很好用。
建议，安装cloudreve时让用户自己输入邮箱设置管理员账号
现在只能用默认账号admin@cloudreve.org
谢谢！

**Comment by wh7** [comment]
可以修改的，网页右上角「管理面板」——左侧菜单「用户」。

**Comment by kirin10000** [comment]
脚本只是帮您安装cloudreve，具体用法可以去看cloudreve的文档，有什么疑问也可以在cloudreve开issue

https://github.com/cloudreve/Cloudreve
