### ISSUE TITLE
如何开启TFO

### ISSUE THREAD

**Issue by CCCAUCHY** [kirin10000/Xray-script#109]
客户端：Windows 10 21H2 19044.1503 Qv2ray 2.7.0:7000 Xray 1.5.2 
"streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "sockopt": {
                    "tcpFastOpen": true
                },
服务端：Linux arm 5.11.0-1027-oracle #30~20.04.1-Ubuntu Xray 1.5.2 
cat /proc/sys/net/ipv4/tcp_fastopen
3
"streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "sockopt": {
                    "tcpFastOpen": 128
                },

wireshark实测没有TFO

**Comment by cxw620** [comment]
> tcpFastOpen

不建议开启, 参考[这篇文章](https://v2raytech.com/donot-use-tcp-fast-open/)

**Comment by kirin10000** [comment]
> 客户端：Windows 10 21H2 19044.1503 Qv2ray 2.7.0:7000 Xray 1.5.2 "streamSettings": { "network": "tcp", "security": "xtls", "sockopt": { "tcpFastOpen": true }, 服务端：Linux arm 5.11.0-1027-oracle #30~20.04.1-Ubuntu Xray 1.5.2 cat /proc/sys/net/ipv4/tcp_fastopen 3 "streamSettings": { "network": "tcp", "security": "xtls", "sockopt": { "tcpFastOpen": 128 },
> 
> wireshark实测没有TFO

这么配置其实服务端已经开启TFO了，没有增加是因为客户端没有开启，使用支持TFO的浏览器访问伪装网站可以看到TFO连接数增加。
这个问题我以前在上游问过，他们说客户端的TFO功能删掉了，因为不安全。

@CCCAUCHY
