### ISSUE TITLE
大佬能整个真的nextcloud组合方案吗

### ISSUE THREAD

**Issue by crackerjohn** [kirin10000/Xray-script#11]
感觉nextcloud还是挺好用的，如果能和vless-tcp-xtls结合那就是坠吼的，谢谢大佬。

**Comment by kirin10000** [comment]
一直在想呢，原计划中下一步要添加的功能就是它了，最近比较忙，等忙完了就来弄

**Comment by garypang13** [comment]
能否弄个宝塔面板方案,谢谢.

**Comment by kirin10000** [comment]
https://github.com/kirin10000/Xray-script/commit/054329880ae8ea42aef4f086c168592cbd0fc0b4#diff-dc7e79d279356634b687dead1edb83b2181d4388efb443d3beaba379d9b9743b
nextcloud已上线

**Comment by GWONGJYULEI** [comment]
请问能通过“升级 Xray-TLS+Web”的方式，对 用旧脚本搭建的服务器 进行 增量安装nextcloud吗？

**Comment by kirin10000** [comment]
> 请问能通过“升级 Xray-TLS+Web”的方式，对 用旧脚本搭建的服务器 进行 增量安装nextcloud吗？

目前还不行。只能选择重新安装。重新安装的时候选择使用现有nginx，相当于是增量安装
