### ISSUE TITLE
突然无法使用grpc和伪装网站，但可以使用xtls

### ISSUE THREAD

**Issue by CCCAUCHY** [kirin10000/Xray-script#110]
操作系统是Oracle Linux 8
设置日志等级为info后，使用命令启动 `/usr/local/bin/xray run -c /usr/local/etc/xray/config.json` 得到以下报错

`[Error] transport/internet/grpc: failed to listen on /dev/shm/xray_unixsocket/grpc.sock > listen unix /dev/shm/xray_unixsocket/grpc.sock: bind: address already in use`

已经尝试reboot，无法解决。不管是访问伪装网站还是连接grpc，nginx完全不输出任何日志。

奇怪的是另一台Ubuntu的机器使用几乎完全一致的配置（伪装网站不同，且报错的这台仅仅在nginx上多了两条location，而且已经正常使用很久了），却一切正常

**Comment by kirin10000** [comment]
手动升级服务端xray可能导致这个问题。
运行脚本，选择升级xray就可以了。（记得先升级脚本

**Comment by CCCAUCHY** [comment]
> 手动升级服务端xray可能导致这个问题。 运行脚本，选择升级xray就可以了。（记得先升级脚本
虽然确实手动升级过，但手动升级xray前就已经有问题了。发现问题前用脚本升级过nginx，升级nginx前没测试过是否有问题，不确定是否为升级nginx所致。

**Comment by CCCAUCHY** [comment]
补充，重新部署了一台Ubuntu的机器，不到一天，伪装网站cloudreve就炸了，但是grpc和xtls都是好的，这个issue所提到的问题机器在把伪装网站从cloudreve改为nextcloud后恢复正常了，问题直到现在都没有复发。
观察到伪装网站或grpc失效时，netstat -nlpt显示有两个nginx进程，而其他好的机器只有一个nginx进程

**Comment by kirin10000** [comment]
> 伪装网站cloudreve就炸了

炸了是什么意思？描述具体一点

> netstat -nlpt显示有两个nginx进程，而其他好的机器只有一个nginx进程

nginx进程数和服务器cpu个数有关，一般等于cpu线程数
