### ISSUE TITLE
通过更新方式从PHP7.4.*更新过后， Nextcloud 与 php 8 不兼容

### ISSUE THREAD

**Issue by Lostsite** [kirin10000/Xray-script#111]
脚本自动更新PHP会更新至PHP 8.1.2 版本，但Nextcloud无法使用PHP8 版本。

**Comment by Lostsite** [comment]
好吧，完全重装后就没问题了，但是如果原来安装的是7.4.*版本的PHP，通过更新方式进行更新，会出问题。

**Comment by kirin10000** [comment]
是的，这个问题没有太好的解决方案。如果网盘东西少的话可以选择重装nextcloud，网盘东西多的话就比较麻烦了
