### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by libea18** [kirin10000/Xray-script#116]
how can i see logs and  error logs in server ?

**Comment by kirin10000** [comment]
modify `/usr/local/etc/xray/config.json`.
 You can see xtls.github.io to see how to set up logging

**Comment by libea18** [comment]
no you didnt understand
i mean  : i wanna View real-time access logs in server ubuntu
another script have this feature like  wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/wulabing/Xray_onekey/main/install.sh" && chmod +x install.sh && bash install.sh
have : 21. 查看 实时访问日志
or another

**Comment by kirin10000** [comment]
may be you want this : `ss -antp | grep xray`

**Comment by libea18** [comment]
![image](https://user-images.githubusercontent.com/67378481/157935892-dc6456f4-f90d-419d-82b0-861cec2401a6.png)
need like this 
xray access log 
if had some error , will display in xray log

**Comment by kirin10000** [comment]
1. edit `/usr/local/etc/xray/config.json`, change `none` to `warning`.
2. restart Xray+tls+web.
3. use `systemctl status xray --all` to see the access log

the log will not flash itself, you should run `systemctl status xray --all` periodically

**Comment by libea18** [comment]
[ Error writing /usr/local/etc/xray/config.json: Permission denied ]
i couldnt edit config.json file

**Comment by libea18** [comment]
couldnt watch this report live?

**Comment by kirin10000** [comment]
> i think need add "access": "/var/log/xray/access.log", "error": "/var/log/xray/error.log", in /usr/local/etc/xray/config.json file but when i add it, xray couldnt restart

you should make sure the folder `/var/log/xray` exists.

**Comment by kirin10000** [comment]
> couldnt watch this report live? continuously please update script and support this feature :(

this script is disigned for personal use, not for bussiness.It doesn't make sense to look at your own access log in Xray server. you can get it in the Xray client

**Comment by kirin10000** [comment]
you can see the real time access log by this.

1. configure log in config.json to `warning` without `access` and `error`
2. start Xray tls +web
3. run `systemctl stop xray`
4. run `/bin/rm -rf /dev/shm/xray`
5. run `/bin/mkdir /dev/shm/xray`
6. run `/bin/chmod 711 /dev/shm/xray`
7. run `/usr/local/bin/xray run -config /usr/local/etc/xray/config.json`

**Comment by libea18** [comment]
solved with add /var/log/xray 
thank you
