### ISSUE TITLE
安装php出错了

### ISSUE THREAD

**Issue by marcyquan** [kirin10000/Xray-script#117]
configure: error: Cannot use external libcrypt as some algo are missing
make: *** No targets specified and no makefile found.  Stop.
php编译失败！
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
在Bug修复前，建议使用Ubuntu最新版系统

**Comment by marcyquan** [comment]
系统是debian10

**Comment by kirin10000** [comment]
从 php-8.1.0 开始 debian 10 编译失败。
请更换debian 11
