### ISSUE TITLE
CA颁发时超时，Processing, The CA is processing your order, please just wait.

### ISSUE THREAD

**Issue by Likebard** [kirin10000/Xray-script#122]
希望默认机构换成letsencrypt，见https://github.com/acmesh-official/acme.sh/issues/3995

**Comment by kirin10000** [comment]
脚本目前的行为是如果默认ca颁发失败则切换为letsencrypt。acmesh将zerossl设为默认ca也是有原因的，zerossl可以无限次申请证书

**Comment by felixlu** [comment]
我的甲骨文机器也有同样问题：
使用 docker swarm 跑的 traefik 可以正常申请 let's encrypt 的证书（说明我的端口和防火墙都没有问题）。
删掉 traefik stack、并且退出 docker swarm 集群模式，用这个安装脚本就一直报和楼主一样的错。看日志里确实有先试 zerossl、再试 let's entrypt，但是都不行。

**Comment by kirin10000** [comment]
> 我的甲骨文机器也有同样问题： 使用 docker swarm 跑的 traefik 可以正常申请 let's encrypt 的证书（说明我的端口和防火墙都没有问题）。 删掉 traefik stack、并且退出 docker swarm 集群模式，用这个安装脚本就一直报和楼主一样的错。看日志里确实有先试 zerossl、再试 let's entrypt，但是都不行。

都不行的话我估计就是你那边的原因了，我也经常遇到zerossl申请失败，然后let's entrypt就成功了
