### ISSUE TITLE
Vultr VPS 和 搬瓦工 VPS 安装一键脚本后 CPU负荷接近100%

### ISSUE THREAD

**Issue by Tigerlee100307** [kirin10000/Xray-script#123]
vultr VPS
![image](https://user-images.githubusercontent.com/59568119/160260707-69f84b04-4359-4cb2-918d-c864df9cb81d.png)
搬瓦工 VPS
![image](https://user-images.githubusercontent.com/59568119/160260753-bf1b01e6-170e-49ed-8f11-523c6e12b73d.png)
以前安装脚本都没有这个问题。

**Comment by kirin10000** [comment]
如果是在安装的过程中，这是正常的。
如果是在安装完成后，多半是你的机器ssh登陆密码设置得太简单，被攻破后植入了挖矿程序。
使用`top`命令查看是什么进程占用这么高的cpu

**Comment by Tigerlee100307** [comment]
你好，我重装系统后在用脚本安装后，还是CPU 100%负荷，两个VPS都是这样。

**Comment by kirin10000** [comment]
请使用`top`命令查看是什么进程占用cpu

**Comment by Tigerlee100307** [comment]
好的

**Comment by asd5946213** [comment]
好像是装bbr时候选择xanmod内核的问题 选xanmod内核版本的时候选第三个stable就没这个问题了

**Comment by Tigerlee100307** [comment]
谢谢，我也再试试
