### ISSUE TITLE
Nginx依赖安装失败

### ISSUE THREAD

**Issue by LYwyc** [kirin10000/Xray-script#125]
阿里云，系统ubuntu20.04

正在安装Nginx依赖。。。
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1.3).
zlib1g-dev set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgd-dev : Depends: libxpm-dev but it is not going to be installed
             Depends: libx11-dev but it is not going to be installed
             Depends: libxt-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Hit:1 http://mirrors.cloud.aliyuncs.com/ubuntu focal InRelease
Hit:2 http://mirrors.cloud.aliyuncs.com/ubuntu focal-updates InRelease
Hit:3 http://mirrors.cloud.aliyuncs.com/ubuntu focal-backports InRelease
Hit:4 http://mirrors.cloud.aliyuncs.com/ubuntu focal-security InRelease
Reading package lists... Done                                
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1.3).
zlib1g-dev set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgd-dev : Depends: libxpm-dev but it is not going to be installed
             Depends: libx11-dev but it is not going to be installed
             Depends: libxt-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
依赖安装失败！！
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
按回车键继续或者Ctrl+c退出

**Comment by LYwyc** [comment]
后续Nginx也顺道编译失败了

**Comment by LYwyc** [comment]
换了一个apt源已经解决了，顺道感谢作者提供做个人网盘的思路，真的太棒了！祝愿作者原来越好

**Comment by kirin10000** [comment]
> 换了一个apt源已经解决了，顺道感谢作者提供做个人网盘的思路，真的太棒了！祝愿作者原来越好

谢谢您的支持
