### ISSUE TITLE
套cdn用不起了

### ISSUE THREAD

**Issue by zmz2580** [kirin10000/Xray-script#129]
套上阿里的cdn后ping可以ping通，伪装网站也能打开，但是线路用不了了

**Comment by kirin10000** [comment]
阿里云的cdn不支持websocket和grpc，用不了

**Comment by cxw620** [comment]
> 阿里云的cdn不支持websocket和grpc，用不了

阿里云CDN支持websocket吧? 我看到官网有计费项, 3块钱还是6块钱1GB

**Comment by zmz2580** [comment]
阿里云的必须是企业账号才能开通websocket，我问了阿里客服了

**Comment by cxw620** [comment]
> 阿里云的必须是企业账号才能开通websocket，我问了阿里客服了

影响不大, 友商可以用就ok

可以参考我的方案https://github.com/kirin10000/Xray-script/issues/133

websocket用腾讯云dcdn或者流媒体加速cdn, grpc走阿里云dcdn或者七牛dcdn, 二者哪个快用哪个, 价格可以控制在150~200一年, 和别人拼个车就差不多了. 特别地, 配合cf ip优选, 教育网ipv6直连香港, 走cf的websocket, 上下传都有>800Mbps(几乎跑满1G物理带宽), 校园网环境用得也挺舒服, 拿来上传文件也很棒(阿里DCDN回源极慢, 下传还好可以跑满带宽; 腾讯云DCDN没流量包不怎么用, 拿来备用的, 速度略慢, 但上传速度还可以; 七牛跟阿里一家的; cf一般上传也是极慢的, 但可能是ipv6校园网加成吧)

仅供参考
