### ISSUE TITLE
想问下套阿里的cdn怎么设置才能正常使用线路

### ISSUE THREAD

**Issue by zmz2580** [kirin10000/Xray-script#132]
目前情况是这样的，套的阿里云的cdn，网站能正常访问，但是线路基于用不了了

**Comment by kirin10000** [comment]
阿里云的cdn不支持websocket和grpc，用不了

**Comment by zmz2580** [comment]
我用腾讯的成功了，正常使用，加密的数据是走cdn转一道再到服务器对吗？

**Comment by kirin10000** [comment]
更新一下就可以了

https://github.com/kirin10000/Xray-script/issues/133
