### ISSUE TITLE
套CDN遇到的问题及临时解决方案

### ISSUE THREAD

**Issue by cxw620** [kirin10000/Xray-script#133]
使用最新版本脚本部署后, 直连正常, 腾讯云DCDN正常但是流媒体加速CDN异常; 阿里云DCDN异常, 七牛DCDN实际上也是基于阿里云的, 也异常, 经开启日志排查, 提示加密套件相关问题, 锁定为xray的这个配置惹出的问题:
```
"cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
```
删除后, 阿里云DCDN, 腾讯云流媒体加速CDN也可以使用了, 贴出来供参考.
同时补充, 阿里云DCDN是支持gRPC的. 速度还OK. 当然也是支持Websocket的, 但是是另外计费的.

**Comment by kirin10000** [comment]
加这一行主要是为了有个网站安全测试网站，可以拿个A+，嘛，也不是那么重要，已经删掉了

**Comment by kirin10000** [comment]
感谢测试，不然这原因还真难发现

**Comment by cxw620** [comment]
顺便提一下吧, 为了安全:
 - nginx的配置中隐藏一下nginx版本号
 -  xray配置添加这个[https://github.com/chika0801/Xray-examples/blob/bdbcff1e5b7a5f8db713848d190d326a6188a9ea/VLESS-TCP-XTLS/config_server.json#L71](https://github.com/chika0801/Xray-examples/blob/bdbcff1e5b7a5f8db713848d190d326a6188a9ea/VLESS-TCP-XTLS/config_server.json#L71)阻止ip访问泄露证书
 
最后, 程序本体可以弄一个一键开启nginx日志和xray日志的debug选项, 方便排查问题. 
此外建议提供手动配置证书的选项, 在自动获取证书前让输入y/n确定, 便于手动配置acme通过dns预验证获取证书.(开了80端口天天有扫描的, 索性关闭了, 443有被探测风险, 也有泄露源站ip风险, 参考[issue](https://github.com/XTLS/Xray-core/issues/1014))

**Comment by kirin10000** [comment]
> 顺便提一下吧, 为了安全:
> 
> * nginx的配置中隐藏一下nginx版本号
> * xray配置添加这个https://github.com/chika0801/Xray-examples/blob/bdbcff1e5b7a5f8db713848d190d326a6188a9ea/VLESS-TCP-XTLS/config_server.json#L71阻止ip访问泄露证书
> 

你说的这两个都是多次一举，伪装网站应该是要和普通的网站更加贴近，无论是个人网站还是大型网站一般都不会刻意去隐藏nginx版本号和网站证书

**Comment by kirin10000** [comment]
> 
> 最后, 程序本体可以弄一个一键开启nginx日志和xray日志的debug选项, 方便排查问题. 此外建议提供手动配置证书的选项, 在自动获取证书前让输入y/n确定, 便于手动配置acme通过dns预验证获取证书.(开了80端口天天有扫描的, 索性关闭了, 443有被探测风险, 也有泄露源站ip风险, 参考[issue](https://github.com/XTLS/Xray-core/issues/1014))
> 

这个用处也不是很大，会的人可以自己去配置，小白也用不上，脚本连xray的log都关了

**Comment by cxw620** [comment]
> > 最后, 程序本体可以弄一个一键开启nginx日志和xray日志的debug选项, 方便排查问题. 此外建议提供手动配置证书的选项, 在自动获取证书前让输入y/n确定, 便于手动配置acme通过dns预验证获取证书.(开了80端口天天有扫描的, 索性关闭了, 443有被探测风险, 也有泄露源站ip风险, 参考[issue](https://github.com/XTLS/Xray-core/issues/1014))
> 
> 这个用处也不是很大，会的人可以自己去配置，小白也用不上，脚本连xray的log都关了

主要是方便排查问题提issue(笑), 不过有道理.

**Comment by cxw620** [comment]
> > 顺便提一下吧, 为了安全:
> > 
> > * nginx的配置中隐藏一下nginx版本号
> > * xray配置添加这个[https://github.com/chika0801/Xray-examples/blob/bdbcff1e5b7a5f8db713848d190d326a6188a9ea/VLESS-TCP-XTLS/config_server.json#L71阻止ip访问泄露证书](https://github.com/chika0801/Xray-examples/blob/bdbcff1e5b7a5f8db713848d190d326a6188a9ea/VLESS-TCP-XTLS/config_server.json#L71%E9%98%BB%E6%AD%A2ip%E8%AE%BF%E9%97%AE%E6%B3%84%E9%9C%B2%E8%AF%81%E4%B9%A6)
> 
> 你说的这两个都是多次一举，伪装网站应该是要和普通的网站更加贴近，无论是个人网站还是大型网站一般都不会刻意去隐藏nginx版本号和网站证书

第二个开启的话, 参考nginx官网nginx.org, 确实版本号没有隐藏, 但如图,
![image](https://user-images.githubusercontent.com/70561268/164986016-e0fed4d8-26e1-4f47-84b6-597fcb112a1b.png)
也是开了这个类似`rejectUnknownSni`阻止直接访问的, nginx配置有一个类似的选项, 80端口也是直接返回444, 更多是出于安全着想吧. 只是提一下😊
