### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by SekiBetu** [kirin10000/Xray-script#139]
无法访问这个网站 https://www.githubstatus.com/
![image](https://user-images.githubusercontent.com/38283893/170851400-5fa529aa-6cbd-4ce2-b5e6-896e55f22e04.png)
同一台服务器用 [别的脚本](https://github.com/mack-a/v2ray-agent) 安装的能访问
![image](https://user-images.githubusercontent.com/38283893/170851412-d015dc81-8100-4c87-a4f4-51dc88fc5a83.png)

**Comment by SekiBetu** [comment]
是不是这个问题啊
https://github.com/XTLS/Xray-core/issues/881#issuecomment-1007132306

**Comment by SekiBetu** [comment]
https://github.com/cloudreve/Cloudreve/issues/728#issuecomment-762260141
还是因为这个问题？我选的伪装方案就是 [Cloudreve](https://github.com/cloudreve/Cloudreve)

**Comment by SekiBetu** [comment]
确实是这个原因，我换成伪装网页就没问题了，看来目前无解

**Comment by SekiBetu** [comment]
不知道为什么，只有在先安装伪装静态网页的再转成网盘才行，直接安装网盘就会出这个错误

**Comment by SekiBetu** [comment]
https://www.linuxfixes.com/2022/03/solved-what-neterrhttp2protocolerror.html#:~:text=I%20disable%20JS).-,Solution,-I%20didn%27t%20figure
百思不得其解了属于是

**Comment by kirin10000** [comment]
代理无法访问这个网站？也许这个网站本身就已经怀掉了呢？

> [cloudreve/Cloudreve#728 (comment)](https://github.com/cloudreve/Cloudreve/issues/728#issuecomment-762260141) 还是因为这个问题？我选的伪装方案就是 [Cloudreve](https://github.com/cloudreve/Cloudreve)

和这个无关

**Comment by kirin10000** [comment]
> 是不是这个问题啊 [XTLS/Xray-core#881 (comment)](https://github.com/XTLS/Xray-core/issues/881#issuecomment-1007132306)

有可能，你试试其他协议比如tcp-tls，或者ws-tls

**Comment by SekiBetu** [comment]
> > 是不是这个问题啊 [XTLS/Xray-core#881 (comment)](https://github.com/XTLS/Xray-core/issues/881#issuecomment-1007132306)
> 
> 我看了下他说的，他的意思好像是访问所有网站都报这个错误，但是你是只访问这一个网站回报错，不太一样。
> 
> 你试试其他协议比如tcp-tls，或者ws-tls

我反复试验了，用别的脚本搭建可以访问，用你的不行，真不知道啥情况了，配置我也看不出什么端倪，可能别的脚本配置少

**Comment by SekiBetu** [comment]
你说有没有可能是因为编译nginx的原因，别的脚本都是用apt安装的

**Comment by SekiBetu** [comment]
我用的就是脚本默认的tcp tls 加上网盘的方案，域名申请选的是子域名非全域

**Comment by SekiBetu** [comment]
nextcloud配置文件是同样适用于cloudreve的嘛，我没选nextcloud nginx配置文件里也有这个

**Comment by kirin10000** [comment]
> 你说有没有可能是因为自编译nginx的原因，别的脚本都是用apt安装的，openssl版本不一样，这边3.0太新了

没有关系，实际上tls解密是xray做的，因为xray核心前置

**Comment by kirin10000** [comment]
> nextcloud配置文件是同样适用于cloudreve的嘛，我没选nextcloud，nginx配置文件里也有这个

没有使用nextcloud的时候，nextcloud配置文件不会生效

**Comment by kirin10000** [comment]
> 
> 我在三台不同运营商的服务器上反复试验了，用别的脚本搭建可以访问，用你的不行，真不知道啥情况了，配置我也看不出什么端倪，可能别的脚本nginx配置少，犯的错误就少

多看看xray配置有什么区别，和nginx  无关，如果你是使用tcp-tls的话，代理的时候知会经过xray ，不会经过nginx

**Comment by kirin10000** [comment]
我想的可能原因有:
1. 脚本申请的证书带有ocsp,并且Xray设置了ocsp
2. 脚本申请的证书是ecc 证书
3. 脚本申请的证书是使用acme.sh默认的zerossl，其他脚本一般是letsencrypt

**Comment by kirin10000** [comment]
对了，你客户端用的代理软件是什么？怎么代理的，是用 http还是socks5，有没有开sniff

**Comment by SekiBetu** [comment]
> 对了，你客户端用的代理软件是什么？怎么代理的，是用 http还是socks5，有没有开sniff

v2rayN加xray内核，版本1.5.5，关闭了sniff，http代理Chrome上的网站，类似上面说的网站之前有碰到过别的，但是没有记录下来，主流网站都没问题

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/174473826-05f15416-c693-4b36-9be0-770b176b29a8.png)
不好意思占用公共资源了，这服务器有问题，本身就连不上
