### ISSUE TITLE
纯IPV6，TCP报错Timeout, WS只支持自选IP

### ISSUE THREAD

**Issue by ygtsj** [kirin10000/Xray-script#14]
V2RAYn测试报错(xray 1.1.4核心)

TCP
 app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp [2a02:180:6:1::2521]:443: connectex: A socket operation was attempted to an unreachable network.] > common/retry: all retry attempts failed

WS
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://qe.ren.kkf/af59158):  > dial tcp: lookup qe.ren.kkf: no such host] > common/retry: all retry attempts failed

WS自选IP正常

**Comment by ygtsj** [comment]
这个是不是无解？别的脚本也是这个情况。。呵呵！！

**Comment by kirin10000** [comment]
@ygtsj 群友遇到了相同的问题，他重启ipv6路由就解决了
