### ISSUE TITLE
能使用 caddy 替换 nginx 吗？

### ISSUE THREAD

**Issue by choicky** [kirin10000/Xray-script#15]
[caddy](https://caddyserver.com/v2) 是集成了LE证书的web服务器，功能与nginx 一样。

如果使用 caddy 替换 nginx， 是不是会更简单一些，并且基本上也具有与 nginx 一样的功能。

**Comment by kirin10000** [comment]
Nginx申请证书也不麻烦，安装时间申请证书只占了很小的一部分。Nginx也能通过apt/yum/dnf安装。对此脚本而言caddy对nginx并没有什么优势
