### ISSUE TITLE
请问大佬该脚本如何配置奈飞使用IPV6？

### ISSUE THREAD

**Issue by hellolink-github** [kirin10000/Xray-script#151]
在文件/usr/local/etc/xray/config.json中添加：
"outbounds": [
    {
      "tag":"IP4_out",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag":"IP6_out",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv6"
      }
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "outboundTag": "IP6_out",
        "domain": ["geosite:netflix","geosite:youtube"]
      },
      {
        "type": "field",
        "outboundTag": "IP4_out",
        "network": "udp,tcp"
      }
    ]
  }
并且下载geosite.dat后，xray无法启动，显示：
xray.service - Xray Service
     Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/xray.service.d
             └─10-donot_touch_single_conf.conf
     Active: failed (Result: exit-code) since Mon 2022-08-01 12:59:43 UTC; 4s ago
       Docs: https://github.com/xtls
    Process: 6623 ExecStartPre=/bin/rm -rf /dev/shm/xray (code=exited, status=0/SUCCESS)
    Process: 6624 ExecStartPre=/bin/mkdir /dev/shm/xray (code=exited, status=0/SUCCESS)
    Process: 6625 ExecStartPre=/bin/chmod 711 /dev/shm/xray (code=exited, status=0/SUCCESS)
    Process: 6626 ExecStart=/usr/local/bin/xray run -config /usr/local/etc/xray/config.json (code=exited, status=23)
    Process: 6630 ExecStopPost=/bin/rm -rf /dev/shm/xray (code=exited, status=0/SUCCESS)
   Main PID: 6626 (code=exited, status=23)
        CPU: 18ms

Aug 01 12:59:43 WIKIHOST-220210LPIXGO systemd[1]: Starting Xray Service...
Aug 01 12:59:43 WIKIHOST-220210LPIXGO systemd[1]: Started Xray Service.
Aug 01 12:59:43 WIKIHOST-220210LPIXGO xray[6626]: Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 linux/amd64)
Aug 01 12:59:43 WIKIHOST-220210LPIXGO xray[6626]: A unified platform for anti-censorship.
Aug 01 12:59:43 WIKIHOST-220210LPIXGO xray[6626]: 2022/08/01 12:59:43 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Aug 01 12:59:43 WIKIHOST-220210LPIXGO xray[6626]: Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/c>
Aug 01 12:59:43 WIKIHOST-220210LPIXGO systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Aug 01 12:59:43 WIKIHOST-220210LPIXGO systemd[1]: xray.service: Failed with result 'exit-code'.
请问大神该如何操作？

**Comment by jaydiao521** [comment]
你最后是怎么解决的，这个脚本的确是不能IPV6分流

**Comment by hellolink-github** [comment]
> 你最后是怎么解决的，这个脚本的确是不能IPV6分流

可以的，我配置文件写的有问题而已
