### ISSUE TITLE
关于使用Vless+Websocket+TLS后，配置文件中streamSettings的配置为xtls的问题

### ISSUE THREAD

**Issue by PatrikYang** [kirin10000/Xray-script#152]
使用一键脚本安装后，选择的安装方式为Vless+Websocket+TLS，打开配置文件后发现配置如下
{
            "port": 443,
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "fallbacks": [
                    {
                        "path": "xxx",
                        "dest": "@/dev/shm/xray/ws.sock"
                    },
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/nginx/h2.sock"
                    },
                    {
                        "dest": "/dev/shm/nginx/default.sock"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "certificates": [
                        {
                            "certificateFile": "xxx",
                            "keyFile": "xxx",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
        },
为何此处的配置不需要UUID？
为何此处配置为xtls呢？
请教一下这块的工作原理。

**Comment by kirin10000** [comment]
预期行为
