### ISSUE TITLE
如何查看日志？或者代理记录，有没有快速打开脚本的命令，还是只能执行那个命令才能打开

### ISSUE THREAD

**Issue by small-white-rabbit** [kirin10000/Xray-script#16]
如题，想查看错误记录或者代理链接信息 但是好像没有入口

进入菜单好像只能 用执行命令 没有快捷的命令？

**Comment by kirin10000** [comment]
vim /usr/local/etc/xray/config.json 将log-level改为warning。重启xray
systemctl status xray 查看日志

**Comment by kirin10000** [comment]
> `_``_`
