### ISSUE TITLE
BBR安装xanmod内核失败

### ISSUE THREAD

**Issue by hellolink-github** [kirin10000/Xray-script#162]
debian11系统，安装BBR时无论选择： 2. 安装/升级最新xanmod内核并启用bbr  (推荐)还是3. 安装/升级最新xanmod内核并启用bbr2 (推荐)后都提示：
获取版本异常
开启bbr2失败
如果刚安装完内核，请先重启
如果重启仍然无效，请尝试选项3
重启后也无效

**Comment by Matrix6677** [comment]
+1

**Comment by kirin10000** [comment]
嗯，xanmod内核上游更新了，我有空会跟进一下

**Comment by jaydiao521** [comment]
+1

**Comment by yangtuo250** [comment]
Install xanmod manully by [https://xanmod.org/#install_via_terminal](https://xanmod.org/#install_via_terminal)
