### ISSUE TITLE
使用xtls-rprx-vision后chrome会报SSL相关错误

### ISSUE THREAD

**Issue by Array-Cats** [kirin10000/Xray-script#169]
表现现象：使用chrome浏览器打开网页时会出现ERR_SSL_VERSION_OR_CIPHER_MISMATCH等SSL相关的错误（总共出现有3个不同的，我只是复制了最后一个）

~~似乎的解决方案：修改config.json中"minVersion": "1.2"修改成"minVersion": "1.3"（至少我修改以后目前没有遇到以上错误）~~

问题似乎是出在1.7.0的core上，根据t友反馈新更新的1.7.1修复了这个问题

**Comment by KevinMX** [comment]
1.7.2 已修复。
