### ISSUE TITLE
使用脚本更新nginx后nginx配置文件的问题

### ISSUE THREAD

**Issue by PaPerseller** [kirin10000/Xray-script#17]
使用此脚本选择更新xray-tls+web，不管是否选择更新nginx，每回都会重新生成/etc/nginx/conf.d/xray.conf文件。能否提供仅更新nginx选项或者不修改xray.conf的选项，以保留有自定义改动的xray.conf版本。

**Comment by kirin10000** [comment]
脚本没有把配置文件存放到额外的文件里。也就是说，
脚本根据nginx和xray配置文件来获取当前配置信息，然后才能执行正常执行升级/以及管理面板里的各种操作。
也就是说，当你自行修改xray.conf或者config.json之后，这个脚本已经不能正常使用了。
一键脚本和高自由度本身就是违背的，一键脚本集成了方便的功能，却也限制了配置的自由。想要自由配置最好还是手动搭建。
当然你也可以在安装完一次之后自由配置，之后再也不用这个脚本了

**Comment by PaPerseller** [comment]
> 脚本没有把配置文件存放到额外的文件里。也就是说，
> 脚本根据nginx和xray配置文件来获取当前配置信息，然后才能执行正常执行升级/以及管理面板里的各种操作。
> 也就是说，当你自行修改xray.conf或者config.json之后，这个脚本已经不能正常使用了。
> ~一键搭建~管理脚本和高自由度本身就是违背的，~一键安装脚本~带有管理功能的脚本集成了方便的功能，却也限制了配置的自由。想要自由配置最好还是手动搭建。
> 当然你也可以在安装完一次之后自由配置，之后再也不用这个脚本了

理解了。目前准备将有自定义改动的文件作备份，有更新后再根据新版调整后重新应用
