### ISSUE TITLE
Cloudreve的3.6.2版本地址不对，下载不到文件了

### ISSUE THREAD

**Issue by lilin151** [kirin10000/Xray-script#173]
下载不到文件的地址：https://github.com/cloudreve/Cloudreve/releases/download/3.6.2/cloudreve_3.6.2_linux_amd64.tar.gz
![image](https://user-images.githubusercontent.com/33724029/217699826-1158a1d5-4e97-4cdb-b5f4-bb6396bb1352.png)

**Comment by carolusliu** [comment]
![image](https://user-images.githubusercontent.com/12553276/218026113-e24e9cb3-7676-474f-8ceb-0d5856481756.png)

**Comment by carolusliu** [comment]
> 下载不到文件的地址：https://github.com/cloudreve/Cloudreve/releases/download/3.6.2/cloudreve_3.6.2_linux_amd64.tar.gz ![image](https://user-images.githubusercontent.com/33724029/217699826-1158a1d5-4e97-4cdb-b5f4-bb6396bb1352.png)

![image](https://user-images.githubusercontent.com/12553276/218030488-09f1e238-5039-41d7-9967-e2a2392e8753.png)

**Comment by lilin151** [comment]
> > 下载不到文件的地址：https://github.com/cloudreve/Cloudreve/releases/download/3.6.2/cloudreve_3.6.2_linux_amd64.tar.gz ![image](https://user-images.githubusercontent.com/33724029/217699826-1158a1d5-4e97-4cdb-b5f4-bb6396bb1352.png)
> 
> ![image](https://user-images.githubusercontent.com/12553276/218030488-09f1e238-5039-41d7-9967-e2a2392e8753.png)



> > 下载不到文件的地址：https://github.com/cloudreve/Cloudreve/releases/download/3.6.2/cloudreve_3.6.2_linux_amd64.tar.gz ![image](https://user-images.githubusercontent.com/33724029/217699826-1158a1d5-4e97-4cdb-b5f4-bb6396bb1352.png)
> 
> ![image](https://user-images.githubusercontent.com/12553276/218030488-09f1e238-5039-41d7-9967-e2a2392e8753.png)

本地我知道怎么处理，把cloudreve的版本号改一下，再把脚本的检查更新屏了就可以了，只是提个issus给作者反馈一下（之前cloudreve3.6.2版本是能下载的，应该是cloudreve的作者把3.6.2的版本给撤回了）
![image](https://user-images.githubusercontent.com/33724029/218034305-1f5c6f04-e753-4b63-b9d1-571f4985b93f.png)

**Comment by kirin10000** [comment]
![image](https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png)
