### ISSUE TITLE
vps关机以后无法重新开机了

### ISSUE THREAD

**Issue by bjzhili** [kirin10000/Xray-script#18]

**Comment by bjzhili** [comment]
vps关机以后在开机无法开机了

**Comment by kirin10000** [comment]
是更换内核后重启吗？

**Comment by bjzhili** [comment]
谢谢大佬回复。重启以后ip地址不通ssh连接不上，但是谷歌云显示vps已经启动，装了两次都这样没有装bbr的时候正常可以重启

**Comment by kirin10000** [comment]
你得说清楚是什么时候重启，到哪一步重启。
比如说，还没运行脚本就重启，这肯定和脚本无关呀

**Comment by kirin10000** [comment]
请问你装bbr使用的是哪个选项呢？
还有你的系统版本

**Comment by bjzhili** [comment]
用的谷歌云，版本是debian9 和10都用过。用的bbr plus

**Comment by bjzhili** [comment]
用过的谷歌云，版本是debian9和10，用的bbr plus。祝新年顺心顺意，健康开心

**Comment by kirin10000** [comment]
> 祝新年顺心顺意，健康开心

感谢。

> 用过的谷歌云，版本是debian9和10，用的bbr plus。

![image](https://user-images.githubusercontent.com/57820613/103433389-2d2a8c80-4c2b-11eb-8c01-c762d7436005.png)
请看说明。
更换bbrplus的内核第一次启动可能比较久，你稍微等久一点。如果实在无法启动，请去 https://github.com/chiakge/Linux-NetSpeed 提问。安装bbrplus使用的是他的脚本
