### ISSUE TITLE
更新系统软件导致vps无法启动

### ISSUE THREAD

**Issue by jinguang-dong** [kirin10000/Xray-script#19]
Hi Kirin10000 
昨天尝试了一下脚本使用方式(vless-tcp+xtls ) + (vless-websocket + tls) + web 方式安装，发现VPS 通过ssh 22的端口号再也访问不了了，从日志上判断是端口号22被修改所致
但是从脚本中Xray-TLS+Web-setup.sh 并没有看到直接修改ssh 端口号22的地方，还请帮忙分析一下原因，谢谢
````
  420         if ! [[ "$(cat /etc/ssh/sshd_config | grep -i '^[ '$'\t]*port ' | awk '{print $2}')" =~ ^("22"|"")$ ]]; then
  421             red "检测到ssh端口号被修改"
  422             red "升级系统后ssh端口号可能恢复默认值(22)"
  423             yellow "按回车键继续。。。"
  424             read -s
  425         fi
````

```
  270 #配置sshd
  271 check_ssh_timeout()
  272 {
  273     if grep -q "#This file has been edited by Xray-TLS-Web-setup-script" /etc/ssh/sshd_config; then
  274         return 0
  275     fi
  276     echo -e "\n\n\n"
  277     tyblue "------------------------------------------"
  278     tyblue " 安装可能需要比较长的时间(5-40分钟)"
  279     tyblue " 如果中途断开连接将会很麻烦"
  280     tyblue " 设置ssh连接超时时间将有效降低断连可能性"
  281     tyblue "------------------------------------------"
  282     choice=""
  283     while [ "$choice" != "y" -a "$choice" != "n" ]
  284     do
  285         tyblue "是否设置ssh连接超时时间？(y/n)"
  286         read choice
  287     done
  288     if [ $choice == y ]; then
  289         sed -i '/^[ \t]*ClientAliveInterval[ \t]/d' /etc/ssh/sshd_config
  290         sed -i '/^[ \t]*ClientAliveCountMax[ \t]/d' /etc/ssh/sshd_config
  291         echo >> /etc/ssh/sshd_config
  292         echo "ClientAliveInterval 30" >> /etc/ssh/sshd_config
  293         echo "ClientAliveCountMax 60" >> /etc/ssh/sshd_config
  294         echo "#This file has been edited by Xray-TLS-Web-setup-script" >> /etc/ssh/sshd_config
  295         service sshd restart
  296         green  "----------------------配置完成----------------------"
  297         tyblue " 请重新进行ssh连接(即重新登陆服务器)，并再次运行此脚本"
  298         yellow " 按回车键退出。。。。"
  299         read -s
  300         exit 0
  301     fi
  302 }
```

**Comment by kirin10000** [comment]
脚本里没有修改ssh端口的代码，只有检测的代码。
可能是升级系统vps重启开不了机了吧？

**Comment by kirin10000** [comment]
> 昨天尝试了一下脚本使用方式(vless-tcp+xtls ) + (vless-websocket + tls) + web 方式安装，发现VPS 通过ssh 22的端口号再也访问不了了，从日志上判断是端口号22被修改所致

请问这个日志是指？

**Comment by jinguang-dong** [comment]
谢谢您的及时回复，是通过ssh -v 命令登录时的调试日志了解到的,具体日志如下：
ssh -v  -p 22 username@**vps-ip-address**
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to **vps-ip-address** [**vps-ip-address**] port 22.
debug1: connect to address **vps-ip-address** port 22: Connection refused
ssh: connect to host **vps-ip-address**  port 22: Connection refused

另外有个疑问，是什么情况下升级vps会导致vps系统异常，而无法正常开机呢？
PS： VPS的ubuntu 系统为 Ubuntu 20.04 LTS，安装过程中已选择不升级系统镜像了

**Comment by kirin10000** [comment]
> 谢谢您的及时回复，是通过ssh -v 命令登录时的调试日志了解到的,具体日志如下：
> ssh -v -p 22 username@**vps-ip-address**
> OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f 31 Mar 2020
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
> debug1: /etc/ssh/ssh_config line 21: Applying options for *
> debug1: Connecting to **vps-ip-address** [**vps-ip-address**] port 22.
> debug1: connect to address **vps-ip-address** port 22: Connection refused
> ssh: connect to host **vps-ip-address** port 22: Connection refused
> 

我想要的不是这个日志，是安装过程的日志。

> 另外有个疑问，是什么情况下升级vps会导致vps系统异常，而无法正常开机呢？
> PS： VPS的ubuntu 系统为 Ubuntu 20.04 LTS，安装过程中已选择不升级系统镜像了

如果选择的是“仅更新已安装软件”，那么只会运行
```
apt update
apt -y --purge --autoremove full-upgrade(相当于：apt -y full-upgrade && apt --purge autoremove)
```
这都是非常通用的指令，几乎不可能影响系统稳定性。
更新openssh-server软件包时，可能会恢复ssh默认配置，即默认端口22。

**Comment by kirin10000** [comment]
另外，你确定是`ssh port 22的端口号被误修改` ？如果不能通过其它方式确定vps成功开机，建议把标题改成
`更新系统软件导致vps无法启动`

**Comment by jinguang-dong** [comment]
@kirin10000  由于急用，VPS服务器已重装，无法还原现场，采取了以前老的一键配置脚本 vmess + tls+ws 的配置的方式
等以后有时间了在尝试一下“vless-tcp+xtls”一键配置脚本
此问题先关闭了，谢谢
