### ISSUE TITLE
为什么要卸载ufw啊？

### ISSUE THREAD

**Issue by EaglePPP** [kirin10000/Xray-script#193]
为什么要卸载ufw啊？说明没写注意事项，还是自动操作，没有确认选项，我配置了半天的规则就都没了。。

**Comment by LYwyc** [comment]
我也想知道，应该是大佬觉得搭个梯子而已，没必要上防火墙吧

**Comment by kirin10000** [comment]
有的VPS预设了规则，80 443端口都访问不了，我之后会注意一下写到说明里

**Comment by LYwyc** [comment]
> 

大佬请问下，用的搬瓦工没有网页端防火墙的VPS，装完您的nextcloud还需要装ufw不？是不是要配置仅22，80/tcp，443/tcp？

**Comment by LYwyc** [comment]
> 有的VPS预设了规则，80 443端口都访问不了，我之后会注意一下写到说明里



> 有的VPS预设了规则，80 443端口都访问不了，我之后会注意一下写到说明里

大佬请问下，用的搬瓦工没有网页端防火墙的VPS，装完您的nextcloud还需要装ufw不？是不是要配置仅22，80/tcp，443/tcp？

**Comment by bluejerry2021** [comment]
> > 有的VPS预设了规则，80 443端口都访问不了，我之后会注意一下写到说明里
> 
> 大佬请问下，用的搬瓦工没有网页端防火墙的VPS，装完您的nextcloud还需要装ufw不？是不是要配置仅22，80/tcp，443/

> > 有的VPS预设了规则，80 443端口都访问不了，我之后会注意一下写到说明里
> 
> 大佬请问下，用的搬瓦工没有网页端防火墙的VPS，装完您的nextcloud还需要装ufw不？是不是要配置仅22，80/tcp，443/tcp？

装UFW主要是为了安全，防止别人乱扫端口，随意。

**Comment by kirin10000** [comment]
添加了询问
