### ISSUE TITLE
CentOS8 新vps依赖和nginx还是失败

### ISSUE THREAD

**Issue by Nonosword** [kirin10000/Xray-script#20]
您的选择是：1
./Xray-TLS+Web-setup.sh: line 1715: apt: command not found
Error:
Package redhat-lsb-core is not installed.
./Xray-TLS+Web-setup.sh: line 164: lsb_release: command not found
CentOS Linux 8 - AppStream                                                              3.8 MB/s | 6.3 MB     00:01    
CentOS Linux 8 - BaseOS                                                                 2.1 MB/s | 2.3 MB     00:01    
CentOS Linux 8 - Extras                                                                  23 kB/s | 8.6 kB     00:00    
ELRepo.org Community Enterprise Linux Repository - el8                                  186 kB/s | 207 kB     00:01    
Package ca-certificates-2020.2.41-80.0.el8_2.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
正在删除阿里云盾和腾讯云盾 (仅对阿里云和腾讯云服务器有效)。。。
Failed to stop cloudmonitor.service: Unit cloudmonitor.service not loaded.
./Xray-TLS+Web-setup.sh: line 324: /etc/rc.d/init.d/cloudmonitor: No such file or directory
Failed to stop aliyun.service: Unit aliyun.service not loaded.
Failed to disable unit: Unit file aliyun.service does not exist.
./Xray-TLS+Web-setup.sh: line 333: apt: command not found
No match for argument: aliyun_assist
No packages marked for removal.
Dependencies resolved.
Nothing to do.
Complete!
./Xray-TLS+Web-setup.sh: line 342: /etc/init.d/aegis: No such file or directory
./Xray-TLS+Web-setup.sh: line 350: /usr/local/qcloud/stargate/admin/uninstall.sh: No such file or directory
./Xray-TLS+Web-setup.sh: line 351: /usr/local/qcloud/YunJing/uninst.sh: No such file or directory
./Xray-TLS+Web-setup.sh: line 352: /usr/local/qcloud/monitor/barad/admin/uninstall.sh: No such file or directory
Failed to stop YDService.service: Unit YDService.service not loaded.
Failed to disable unit: Unit file YDService.service does not exist.
.
.
.
您的选择是：3
正在安装依赖。。。。
Last metadata expiration check: 0:00:49 ago on Sat 02 Jan 2021 04:00:15 PM UTC.
No match for argument: gperftools-devel
No match for argument: libatomic_ops-devel
No match for argument: geoip-devel
Package wget-1.19.5-10.el8.x86_64 is already installed.
Package unzip-6.0-43.el8.x86_64 is already installed.
Package curl-7.61.1-14.el8.x86_64 is already installed.
Package openssl-1:1.1.1g-11.el8.x86_64 is already installed.
Package crontabs-1.11-16.20150630git.el8.noarch is already installed.
Error: Unable to find a match: gperftools-devel libatomic_ops-devel geoip-devel
CentOS Linux 8 - ContinuousRelease                                                      562  B/s | 257  B     00:00    
CentOS Linux 8 - Debuginfo                                                              1.6 MB/s |  17 MB     00:10    
CentOS Linux 8 - Devel WARNING! FOR BUILDROOT USE ONLY!                                  40 kB/s |  15 kB     00:00    
CentOS Linux 8 - FastTrack                                                              641  B/s | 257  B     00:00    
CentOS Linux 8 - HighAvailability                                                       969 kB/s | 504 kB     00:00    
CentOS Linux 8 - Media - BaseOS                                                         0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'media-baseos':
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrecorder/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrecorder/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/CentOS/BaseOS/repodata/repomd.xml [Couldn't open file /media/CentOS/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrom/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrom/BaseOS/repodata/repomd.xml]
Error: Failed to download metadata for repo 'media-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
依赖安装失败！！
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
按回车键继续或者ctrl+c退出
./Xray-TLS+Web-setup.sh: line 1742: apt: command not found
58 files removed
正在编译Nginx。。。。
--2021-01-02 16:02:30--  https://nginx.org/download/nginx-1.19.6.tar.gz
Resolving nginx.org (nginx.org)... 3.125.197.172, 52.58.199.22, 2a05:d014:edb:5702::6, ...
Connecting to nginx.org (nginx.org)|3.125.197.172|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1055982 (1.0M) [application/octet-stream]
Saving to: ‘nginx-1.19.6.tar.gz’

nginx-1.19.6.tar.gz           100%[=================================================>]   1.01M  1.34MB/s    in 0.8s    

2021-01-02 16:02:31 (1.34 MB/s) - ‘nginx-1.19.6.tar.gz’ saved [1055982/1055982]

--2021-01-02 16:02:31--  https://github.com/openssl/openssl/archive/openssl-3.0.0-alpha9.tar.gz
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/openssl/openssl/tar.gz/openssl-3.0.0-alpha9 [following]
--2021-01-02 16:02:32--  https://codeload.github.com/openssl/openssl/tar.gz/openssl-3.0.0-alpha9
Resolving codeload.github.com (codeload.github.com)... 192.30.255.120
Connecting to codeload.github.com (codeload.github.com)|192.30.255.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14191784 (14M) [application/x-gzip]
Saving to: ‘openssl-openssl-3.0.0-alpha9.tar.gz’

openssl-openssl-3.0.0-alpha9. 100%[=================================================>]  13.53M  45.7MB/s    in 0.3s    

2021-01-02 16:02:32 (45.7 MB/s) - ‘openssl-openssl-3.0.0-alpha9.tar.gz’ saved [14191784/14191784]

checking for OS
 + Linux 5.10.4-1.el8.elrepo.x86_64 x86_64
checking for C compiler ... not found

./configure: error: C compiler cc is not found

./Xray-TLS+Web-setup.sh: line 1083: make: command not found
nginx编译失败！
请尝试更换系统，建议使用Ubuntu最新版系统
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持

**Comment by Nonosword** [comment]
安装时有两条command not found

**Comment by kirin10000** [comment]
发现一个小错误，已更新，请再次尝试安装

**Comment by Nonosword** [comment]
仍然有些问题，安装，以及依赖、nginx ↓


您的选择是：1
./Xray-TLS+Web-setup.sh: line 1715: apt: command not found
redhat-lsb-core-4.1-47.el8.x86_64 marked as user installed.
ca-certificates-2020.2.41-80.0.el8_2.noarch marked as user installed.

------------------------------------------
 安装可能需要比较长的时间(5-40分钟)
 如果中途断开连接将会很麻烦
 设置ssh连接超时时间将有效降低断连可能性
------------------------------------------
是否设置ssh连接超时时间？(y/n)
n
正在删除阿里云盾和腾讯云盾 (仅对阿里云和腾讯云服务器有效)。。。
Failed to stop cloudmonitor.service: Unit cloudmonitor.service not loaded.
./Xray-TLS+Web-setup.sh: line 324: /etc/rc.d/init.d/cloudmonitor: No such file or directory
Failed to stop aliyun.service: Unit aliyun.service not loaded.
Failed to disable unit: Unit file aliyun.service does not exist.
./Xray-TLS+Web-setup.sh: line 333: apt: command not found
No match for argument: aliyun_assist
No packages marked for removal.
Dependencies resolved.
Nothing to do.
Complete!
./Xray-TLS+Web-setup.sh: line 342: /etc/init.d/aegis: No such file or directory
./Xray-TLS+Web-setup.sh: line 350: /usr/local/qcloud/stargate/admin/uninstall.sh: No such file or directory
./Xray-TLS+Web-setup.sh: line 351: /usr/local/qcloud/YunJing/uninst.sh: No such file or directory
./Xray-TLS+Web-setup.sh: line 352: /usr/local/qcloud/monitor/barad/admin/uninstall.sh: No such file or directory
Failed to stop YDService.service: Unit YDService.service not loaded.
Failed to disable unit: Unit file YDService.service does not exist.
.
.
.
您的选择是：3
正在安装依赖。。。。
CentOS Linux 8 - AppStream                                                              7.2 MB/s | 6.3 MB     00:00    
CentOS Linux 8 - BaseOS                                                                 5.0 MB/s | 2.3 MB     00:00    
CentOS Linux 8 - Extras                                                                  30 kB/s | 8.6 kB     00:00    
ELRepo.org Community Enterprise Linux Repository - el8                                   97 kB/s | 207 kB     00:02    
No match for argument: gperftools-devel
No match for argument: libatomic_ops-devel
No match for argument: geoip-devel
Package wget-1.19.5-10.el8.x86_64 is already installed.
Package unzip-6.0-43.el8.x86_64 is already installed.
Package curl-7.61.1-14.el8.x86_64 is already installed.
Package make-1:4.2.1-10.el8.x86_64 is already installed.
Package openssl-1:1.1.1g-11.el8.x86_64 is already installed.
Package crontabs-1.11-16.20150630git.el8.noarch is already installed.
Error: Unable to find a match: gperftools-devel libatomic_ops-devel geoip-devel
Error: Unknown repo: 'epel'
CentOS Linux 8 - ContinuousRelease                                                      487  B/s | 257  B     00:00    
CentOS Linux 8 - Debuginfo                                                              1.6 MB/s |  17 MB     00:10    
CentOS Linux 8 - Devel WARNING! FOR BUILDROOT USE ONLY!                                  39 kB/s |  15 kB     00:00    
CentOS Linux 8 - FastTrack                                                              476  B/s | 257  B     00:00    
CentOS Linux 8 - HighAvailability                                                       571 kB/s | 504 kB     00:00    
CentOS Linux 8 - Media - BaseOS                                                         0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'media-baseos':
  - Curl error (37): Couldn't read a file:// file for file:///media/CentOS/BaseOS/repodata/repomd.xml [Couldn't open file /media/CentOS/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrom/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrom/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrecorder/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrecorder/BaseOS/repodata/repomd.xml]
Error: Failed to download metadata for repo 'media-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
依赖安装失败！！
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
按回车键继续或者ctrl+c退出
./Xray-TLS+Web-setup.sh: line 1742: apt: command not found
58 files removed
正在编译Nginx。。。。
--2021-01-02 16:36:14--  https://nginx.org/download/nginx-1.19.6.tar.gz
Resolving nginx.org (nginx.org)... 3.125.197.172, 52.58.199.22, 2a05:d014:edb:5702::6, ...
Connecting to nginx.org (nginx.org)|3.125.197.172|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1055982 (1.0M) [application/octet-stream]
Saving to: ‘nginx-1.19.6.tar.gz’

nginx-1.19.6.tar.gz           100%[=================================================>]   1.01M   856KB/s    in 1.2s    

2021-01-02 16:36:16 (856 KB/s) - ‘nginx-1.19.6.tar.gz’ saved [1055982/1055982]

--2021-01-02 16:36:16--  https://github.com/openssl/openssl/archive/openssl-3.0.0-alpha9.tar.gz
Resolving github.com (github.com)... 52.69.186.44
Connecting to github.com (github.com)|52.69.186.44|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/openssl/openssl/tar.gz/openssl-3.0.0-alpha9 [following]
--2021-01-02 16:36:17--  https://codeload.github.com/openssl/openssl/tar.gz/openssl-3.0.0-alpha9
Resolving codeload.github.com (codeload.github.com)... 13.112.159.149
Connecting to codeload.github.com (codeload.github.com)|13.112.159.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘openssl-openssl-3.0.0-alpha9.tar.gz’

openssl-openssl-3.0.0-alpha9.     [          <=>                                     ]  13.53M  7.21MB/s    in 1.9s    

2021-01-02 16:36:19 (7.21 MB/s) - ‘openssl-openssl-3.0.0-alpha9.tar.gz’ saved [14191784]

checking for OS
 + Linux 5.10.4-1.el8.elrepo.x86_64 x86_64
checking for C compiler ... not found

./configure: error: C compiler cc is not found

make: *** No rule to make target 'build', needed by 'default'.  Stop.
nginx编译失败！
请尝试更换系统，建议使用Ubuntu最新版系统
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持

**Comment by kirin10000** [comment]
虽然还有问题但是仔细观察log已经不一样了。
重置vps试试呢？

**Comment by kirin10000** [comment]
> Error: Unable to find a match: gperftools-devel libatomic_ops-devel geoip-devel
> Error: Unknown repo: 'epel'

您的centos缺少epel源，请手动添加
具体做法百度 "centos 8 添加epel源" ，这里就不赘述了。
建议你先重置vps，然后手动添加epel源，然后再运行脚本安装

**Comment by Nonosword** [comment]
> > Error: Unable to find a match: gperftools-devel libatomic_ops-devel geoip-devel
> > Error: Unknown repo: 'epel'
> 
> 您的centos缺少epel源，请手动添加
> 具体做法百度 "centos 8 添加epel源" ，这里就不赘述了。
> 建议你先重置vps，然后手动添加epel源，然后再运行脚本安装
> 
> 注：epel源是非常常见的，一般的vps都有自带

我试一下，centos8新vps确实没有epel，连screen都没有

**Comment by Nonosword** [comment]
应该是阔以了，因为拿了个新vps用，域名验证没通过，不过原来的问题不在了
