### ISSUE TITLE
Menu error

### ISSUE THREAD

**Issue by AlanNeverStopWin** [kirin10000/Xray-script#201]
Dear kirin10000:
    The menu numbers 22, 23, 24 in the script are incorrect; they do not point to the correct functionality. I have provided a correct version.

    tyblue "  22. 修改gRPC协议serviceName"
    tyblue "  23. 修改WebSocket协议path(路径)"
    tyblue "  24. 重新生成密钥对(修改REALITY协议publicKey)"

**Comment by kirin10000** [comment]
感谢指正
