### ISSUE TITLE
现有的nginx配置文件如何增加 PHP 的支持？

### ISSUE THREAD

**Issue by choicky** [kirin10000/Xray-script#21]
我按照现有的LEMP文档安装 php-fpm后修改nginx的配置文件 xray.conf 以增加 PHP支持，但浏览器访问PHP时依然是空白的。不知原因在哪。能指点一下吗？

**Comment by kirin10000** [comment]
在xray.conf中是可以配置php的，可能你配置错了。具体php配置方法就不要讨论了，与脚本无关
