### ISSUE TITLE
V2Ray 4.33.0底层传输无法使用XTLS，只能设置为TLS，请问如何解决呢？

### ISSUE THREAD

**Issue by Sh1ron** [kirin10000/Xray-script#24]
客户端为V2rayN v3.27，V2Ray 4.33.0底层传输无法使用XTLS，只能设置为TLS，请问如何解决呢？就是底层传输设置为TLS可以使用，改为XTLS就失败

**Comment by vernala** [comment]
4.32以后已经删除 xtls了，切换成xray核心或者使用4.32版本，具体看v2ray  release版本的change说明
