### ISSUE TITLE
无法获取当前“拥塞控制算法”、“队列算法”

### ISSUE THREAD

**Issue by GWONGJYULEI** [kirin10000/Xray-script#25]
- 系统：Debian 10
- 脚本版本：目前最新的版本
- 使用方法：非 root 用户登录 SSH 后提权至 root，再运行脚本

下面是日志内容：
>  当前内核版本：5.10.4-xanmod
>  最新内核版本：5.11-rc3
>  当前内核是否支持bbr：
>      是
>    当前拥塞控制算法：
> ./Xray-TLS+Web-setup.sh: line 774: sysctl: command not found
>         (bbr未启用)
>    当前队列算法：
> ./Xray-TLS+Web-setup.sh: line 786: sysctl: command not found

非 root 用户单独执行以下命令，却能输出正确的内容：
`sudo sysctl net.ipv4.tcp_congestion_control | cut -d = -f 2 | awk '{print $1}'`
> bbr

`sudo sysctl net.core.default_qdisc | cut -d = -f 2 | awk '{print $1}'`
> fq_pie

因为该问题不影响脚本的使用，作者大可等到心情好的时候再去看看的，谢谢。

**Comment by GWONGJYULEI** [comment]
刚重装了系统再次测试，发现了提权后的 root 并不是一个完整的 root，有使用的限制

**Comment by kirin10000** [comment]
说实话，这个我也不是很懂，，

**Comment by GWONGJYULEI** [comment]
> 说实话，这个我也不是很懂，，

通过简单的测试发现：
- 非 root 用户登录 SSH 后，通过命令：
 `su root`
登录到 root 用户再运行脚本、或者以 sudo 身份运行脚本
`sudo ./Xray-TLS+Web-setup.sh`
均不能完美运行脚本
- 而直接用 root 登录 SSH 后，能完美运行脚本

我重装系统前的 SSH 配置，跟 [🍉老师教程](https://xtls.github.io/documents/level-0/ch04-security/)中所讲的一样。现在为了能运行脚本、使用完整的 root 用户，我没有禁止 root 用户登录 SSH，而是用了带密码的 RSA 私钥来让 root 用户通过 RSA 密钥对登录 SSH

**Comment by kirin10000** [comment]
试试`sudo bash -c "sysctl net.core.default_qdisc | cut -d = -f 2 | awk '{print $1}'"`
