### ISSUE TITLE
[功能请求]不安装nginx等，回落指向另一个http网站（自定义http网站）

### ISSUE THREAD

**Issue by Fhokud** [kirin10000/Xray-script#26]
我想到了一个神奇的操作，直接填写某个支持http访问的网站做web内容来源。
例如linux源站

**Comment by kirin10000** [comment]
这也不是什么神奇的操作，你可以自己弄。
只有反代局限性比较强，脚本不会添加这个功能

**Comment by Fhokud** [comment]
可以设置不安装nginx等吗？

**Comment by kirin10000** [comment]
@Fhokud 可以。但是脚本整体框架要修改，脚本申请证书要用nginx，配置文件存放在nginx里，证书文件存放在nginx里。为了一个已经存在的功能，意义不大。并且反向代理伪装不推荐使用

**Comment by Fhokud** [comment]
acme不是可以独立申请证书的吗？

**Comment by kirin10000** [comment]
> acme不是可以独立申请证书的吗？

@Fhokud 可以
