### ISSUE TITLE
依赖安装失败

### ISSUE THREAD

**Issue by GWONGJYULEI** [kirin10000/Xray-script#27]
- 系统：Debian 10
- 脚本运行用户：root
- 脚本版本：发表前最新版本

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package libjpeg-turbo8-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'libjpeg-turbo8-dev' has no installation candidate
> E: Unable to locate package libfreetype-dev
> Hit:1 http://deb.debian.org/debian buster InRelease
> Get:2 http://deb.debian.org/debian-security buster/updates InRelease [65.4 kB]
> Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
> Hit:4 http://deb.xanmod.org releases InRelease
> Fetched 117 kB in 1s (120 kB/s)  
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package libjpeg-turbo8-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'libjpeg-turbo8-dev' has no installation candidate
> E: Unable to locate package libfreetype-dev
> 依赖安装失败！！
> 欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
> 按回车键继续或者ctrl+c退出

感谢作者的付出！对于 Nextcloud 有一个想法，可以分为“以最低配置安装”和“最佳配置安装”，满足不同配置服务器的性能要求。

**Comment by kirin10000** [comment]
感谢反馈

**Comment by kirin10000** [comment]
> > 依赖安装失败！！

你看还有没有问题。

> 感谢作者的付出！对于 Nextcloud 有一个想法，可以分为“以最低配置安装”和“最佳配置安装”，满足不同配置服务器的性能要求。

nextcloud没法调配置。以后打算加入cloudreve，轻量化的网盘服务
