### ISSUE TITLE
编译nginx 会断开

### ISSUE THREAD

**Issue by sxml** [kirin10000/Xray-script#28]
update_xray_tls_web/nginx-1.19.6/../openssl-openssl-3.0.0-alpha10/.openssl/lib/engines-3\"" -DMODULESDIR="\"/temp_install_update_xray_tls_web/nginx-1.19.6/../openssl-openssl-3.0.0-alpha10/.openssl/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DZLIB -DZLIB_SHARED -DNDEBUG  -MMD -MF crypto/sm2/libcrypto-lib-sm2_err.d.tmp -MT crypto/sm2/libcrypto-lib-sm2_err.o -c -o crypto/sm2/libcrypto-lib-sm2_err.o crypto/sm2/sm2_err.c

连接断开
每次都要重新再来 麻烦

开启了 ssh连接超时时间啊 ?

**Comment by kirin10000** [comment]
断开连接除了网络环境不好之外也有可能是卡爆了，或者除法了vps自动保护机制，自动重启了。除了`设置ssh连接超时时间`之外，我也想不到其它的能够优化的东西了。实在不行就换脚本吧
