### ISSUE TITLE
请问如何修改配置 使得域名打开时不跳转到www？

### ISSUE THREAD

**Issue by aglent** [kirin10000/Xray-script#29]
我想打开域名时 不要跳转到www前缀
请问该如何修改配置？

**Comment by kirin10000** [comment]
修改/usr/local/nginx/conf.d/xray.conf。
删除第12行的server块，把`一级域名`填到相应`www.一级域名`的后面。重启nginx
注意自己修改配置文件后，脚本的管理功能可能导致文件恢复。

**Comment by kirin10000** [comment]
第二种配置方案，把一个域名拆成两个。
运行重置域名，选择域名解析情况时选择`2.仅某个域名解析到服务器`，然后填入`www.一级域名`。
再运行添加域名，选择`2.仅某个域名解析到服务器`，然后填入`一级域名`。
以此类推

建议第二种方案

**Comment by aglent** [comment]
谢谢指点
不过第二种方法有点怪怪 我看了html里有两个站点文件夹
那么第一种方案里 【把一级域名填到相应www.一级域名的后面】这是修改哪部分？

**Comment by kirin10000** [comment]
> 谢谢指点
> 不过第二种方法有点怪怪 我看了html里有两个站点文件夹
> 那么第一种方案里 【把一级域名填到相应www.一级域名的后面】这是修改哪部分？

把所有`server_name`里面的`www.一级域名`改为`www.一级域名 一级域名`，包括第九行

**Comment by aglent** [comment]
> 
> 
> > 谢谢指点
> > 不过第二种方法有点怪怪 我看了html里有两个站点文件夹
> > 那么第一种方案里 【把一级域名填到相应www.一级域名的后面】这是修改哪部分？
> 
> 把所有`server_name`里面的`www.一级域名`改为`www.一级域名 一级域名`，包括第九行

非常感谢，现在可以了。
我还有一个问题咨询，如果我想同时使用trojan协议，回落到trojan这一段要写在哪里呢？水平有限，自己修改后网站能进，trojan无法连接。
