### ISSUE TITLE
ubuntu 20.04 申请证书失败

### ISSUE THREAD

**Issue by BaileyZyp** [kirin10000/Xray-script#30]
![image](https://user-images.githubusercontent.com/16634459/105876950-67285c00-603a-11eb-940b-36291f9925a5.png)

不知道是不是nginx没启动起来，端口已经全部放行

**Comment by kirin10000** [comment]
调试：
```bash
cp /usr/local/nginx/conf/issue_certs.conf /usr/local/nginx/conf/nginx.conf
systemctl restart nginx
wget http://你的域名
```
附上日志

**Comment by BaileyZyp** [comment]
@kirin10000 
![image](https://user-images.githubusercontent.com/16634459/105955182-d771c480-60b0-11eb-81e9-27d77efa4466.png)

**Comment by kirin10000** [comment]
检查nginx是否启动：
```bash
systemctl status nginx
```
检查80端口是否有监听：
```bash
lsof -i:80
```
检查是不是防火墙原因：
```bash
wget -O- http://127.0.0.1:80
wget -O- http://你的域名
```

**Comment by BaileyZyp** [comment]
@kirin10000 
![image](https://user-images.githubusercontent.com/16634459/106142962-1422e600-61ad-11eb-8dcc-bdb471b51394.png)

**Comment by BaileyZyp** [comment]
@kirin10000 
![image](https://user-images.githubusercontent.com/16634459/106143063-3caae000-61ad-11eb-9553-dcf557deb1f5.png)
应该是防火墙的问题吧

**Comment by BaileyZyp** [comment]
@kirin10000 
![image](https://user-images.githubusercontent.com/16634459/106143640-07eb5880-61ae-11eb-935a-f233588f807e.png)

**Comment by BaileyZyp** [comment]
已解决，方法如下↓

卸载 ufw , 恢复路由表
```
sudo apt remove ufw
sudo iptables-restore < /etc/iptables/rules.v4
```

安装 firewalld，并开放端口
```
sudo apt install firewalld
sudo firewall-cmd  --permanent --zone=public --add-port=80/tcp
sudo firewall-cmd  --permanent --zone=public --add-port=443/tcp
sudo firewall-cmd  --reload
```
