### ISSUE TITLE
第一次访问域名时无法跳转到https

### ISSUE THREAD

**Issue by aglent** [kirin10000/Xray-script#31]
我看nginx配置里已经有add_header Strict-Transport-Security语句了，
但重装系统后第一次输入域名，不会自动跳转到https
访问过一次https://域名后，之后输入域名才会自动跳转。
请问这是什么原因？

**Comment by kirin10000** [comment]
正常的，HSTS信息还没有被浏览器记录
百度HSTS了解更多信息
