### ISSUE TITLE
伪装网页拒绝连接+附带一点小建议

### ISSUE THREAD

**Issue by gfpyc** [kirin10000/Xray-script#34]
问题描述：

两台VPS配置一样，都是VLESS+TCP+WEB，伪装网站选择的静态，VLESS连接都正常，但其中一台浏览器浏览伪装网站拒绝连接，而另一台正常。

自己猜测，由于拒绝连接那台VPS自带安全组，端口不手动开，默认就是阻断，443和80开了，可能还有回落或Nginx的端口需要开放？自己看了一遍配置文件没找到，真的挺认真的找了，但Xray目前还不是太熟悉。

求问还有哪些端口需要开放？或可能是其他原因造成的？

===================================

另外，一点点小建议，如可以请在说明中注明Nginx伪装网站的存放位置（/usr/local/nginx/html），理由如下：

感觉像我这种之前用V2ray（vmess+tls+ws+web）自建而没用脚本的。转过来看到有官方推荐脚本，像我这样觉得会省事就用上脚本的人应该还有。从Ubuntu软件源直接装的Nginx的默认目录不是/var/www/下，而Nginx配置文件在/etc/nginx/下，装了静态就肯定想替换成自己的，结果找半天，说明多一句能帮助不少人节省点时间不是么（毕竟脚本本来就是为了省事）。

最后，感谢各位的辛勤付出。

**Comment by kirin10000** [comment]
先检查Nginx是否运行：`service nginx status`查看
再运行
```
wget -O- http://127.0.0.1:80
```
调试

**Comment by gfpyc** [comment]
> 先检查Nginx是否运行：
> `service nginx status`查看
> 
> 再运行

第一条提醒我了，正如你所判断的Nginx没正常启动，由于另一台正常启动，我压根没往这方面想，反而想的可能是其他问题（比如安全组。）问题已经自行处理，目前运行正常。

同样的问题之前自建的时候也遇到过：

查看Nginx状态后，看到这一条，就知道怎么处理了：

`Feb 05 16:11:49 Chrysoberyl nginx[653]: nginx: [emerg] could not build server_names_hash you should increase server_names_hash_bucket_size 32`

nginx.conf下http块里增加
`server_names_hash_bucket_size 64;`

（改成32没用，一直如此。）

Nginx重载配置，正常重启，伪装网页正常访问。

**问题原因**（不是百分之百确定），可能因为不同家VPS的虚拟技术不同，虚拟CPU上缓存的差异所导致的。

按照Nginx的官方说明，这也有可能是由于域名过长所引起，要求增大server_names_hash_bucket_size，我也曾怀疑域名的确长了，因为我的主域名本来就很长：

12个英文字母.cn，且Nginx没正常启动的VPS上的二级子域名11个英文字母。

我尝试过添加一条只有1个字母的二级子域名A记录指向这台主机（主域名显然是没法改的），依然会出现同样的错误，而运作正常的主机同样主域名下，二级子域名5个字母也运行的好好的。

所以只能网上另外的一种说法，与CPU缓存有关，这对大多数使用VPS搭建的人可能造成障碍，毕竟VM的配置肯定不在自己手上。

如果能做的更完美点，将来脚本上是否能够加入检测？当然这是你决定的事了。

总之非常感谢，至少问题找到了。
（也怪我，太久没从头配置，当年很多需要注意的点都忘了，这个问题之前自建的时候其实还是有印象的，用脚本，而不是自己从头到尾来一遍，就疏漏了。）
