### ISSUE TITLE
脚本的节点分享链接v2rayNG无法识别

### ISSUE THREAD

**Issue by 25109548** [kirin10000/Xray-script#37]
v2rayNG版本 1.5.15
脚本版本 2020.01.18

**Comment by 25109548** [comment]
刚刚更新了脚本，版本2020.02.19   依旧无法识别

**Comment by kirin10000** [comment]
链接标准符合：https://github.com/XTLS/Xray-core/issues/91，请去V2RayNG开issue。
VLESS-tcp-xtls的链接应该是可以识别的
