### ISSUE TITLE
Debain9 安装php出现libargon2-dev的依赖错误

### ISSUE THREAD

**Issue by tefiszx** [kirin10000/Xray-script#38]
脚本执行中出现：Unable to locate package libargon2-dev。
然而我已经安装了：apt install libargon2-0-dev。
应该是包名或者文件名出错了。
这是我的包内文件
dpkg-query -L libargon2-0-dev 
/.
/usr
/usr/include
/usr/include/argon2.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libargon2.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libargon2.pc
/usr/share
/usr/share/doc
/usr/share/doc/libargon2-0-dev
/usr/share/doc/libargon2-0-dev/changelog.Debian.amd64.gz
/usr/share/doc/libargon2-0-dev/changelog.Debian.gz
/usr/share/doc/libargon2-0-dev/changelog.gz
/usr/share/doc/libargon2-0-dev/copyright

**Comment by kirin10000** [comment]
感谢反馈

**Comment by kirin10000** [comment]
脚本已更新，请您再试试

**Comment by tefiszx** [comment]
> 脚本已更新，请您再试试
更新脚本后，还是同样的出错提示

您的选择是：6
lsb-release was already set to manually installed.
ca-certificates was already set to manually installed.
wget was already set to manually installed.
--2021-02-24 21:14:33--  https://github.com/kirin10000/Xray-script/raw/main/Xray-TLS+Web-setup.sh
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kirin10000/Xray-script/main/Xray-TLS%2BWeb-setup.sh [following]
--2021-02-24 21:14:33--  https://raw.githubusercontent.com/kirin10000/Xray-script/main/Xray-TLS%2BWeb-setup.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 122538 (120K) [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>] 119.67K  --.-KB/s    in 0.005s  

2021-02-24 21:14:33 (24.8 MB/s) - written to stdout [122538/122538]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20200601~deb9u1).
cron is already the newest version (3.0pl1-128+deb9u1).
g++ is already the newest version (4:6.3.0-4).
gcc is already the newest version (4:6.3.0-4).
lsb-release is already the newest version (9.20161125).
make is already the newest version (4.1-9.1).
net-tools is already the newest version (1.60+git20161116.90da8a0-1).
unzip is already the newest version (6.0-21+deb9u2).
wget is already the newest version (1.18-5+deb9u3).
curl is already the newest version (7.52.1-5+deb9u13).
openssl is already the newest version (1.1.0l-1~deb9u3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libargon2-dev
Get:1 http://deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Get:2 http://security.debian.org stretch/updates InRelease [53.0 kB]     
Ign:3 http://ftp.debian.org/debian stretch InRelease                     
Get:4 http://ftp.debian.org/debian stretch-updates InRelease [93.6 kB]   
Hit:5 http://ftp.debian.org/debian stretch Release                       
Hit:6 https://download.docker.com/linux/debian stretch InRelease
Fetched 238 kB in 1s (199 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libargon2-dev
依赖安装失败！！
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
按回车键继续或者Ctrl+c退出
``

**Comment by tefiszx** [comment]
> 脚本已更新，请您再试试

**Comment by tefiszx** [comment]
> 脚本已更新，请您再试试

把本地脚本修改了一下，替换libargon2-dev为libargon-2-0-dev后，脚本可以运行php的编译流程。然而在编译过程中，发现libpcre的版本过低，最终不能生成makefile，自动退出。Debian9这是要死了。

> checking for libpcre2-8 >= 10.30... no
configure: error: Package requirements (libpcre2-8 >= 10.30) were not met:

Requested 'libpcre2-8 >= 10.30' but version of libpcre2-8 is 10.22

**Comment by kirin10000** [comment]
> > 脚本已更新，请您再试试
> 
> 把本地脚本修改了一下，替换libargon2-dev为libargon-2-0-dev后，脚本可以运行php的编译流程。然而在编译过程中，发现libpcre的版本过低，最终不能生成makefile，自动退出。Debian9这是要死了。
> 
> > checking for libpcre2-8 >= 10.30... no
> > configure: error: Package requirements (libpcre2-8 >= 10.30) were not met:
> 
> Requested 'libpcre2-8 >= 10.30' but version of libpcre2-8 is 10.22

是的 Debian 9 已经不支持编译php了，脚本已经添加检查 @tefiszx
