### ISSUE TITLE
ipv6的vps在域名证书环节出错

### ISSUE THREAD

**Issue by fscarmen** [kirin10000/Xray-script#4]
[Sat Nov 28 03:20:09 PM HKT 2020] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sat Nov 28 03:20:09 PM HKT 2020] Run pre hook:'mv /etc/nginx/conf/nginx.conf /etc/nginx/conf/nginx.conf.bak && cp /etc/nginx/conf/nginx.conf.default /etc/nginx/conf/nginx.conf && sleep 2s && systemctl restart nginx'
[Sat Nov 28 03:20:12 PM HKT 2020] Create account key ok.
[Sat Nov 28 03:20:12 PM HKT 2020] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Sat Nov 28 03:20:14 PM HKT 2020] Registered
[Sat Nov 28 03:20:14 PM HKT 2020] ACCOUNT_THUMBPRINT='xLj8fBZbpvNHgNape12uQBCKRQ49oOxgP1Pah7O1Pn4'
[Sat Nov 28 03:20:14 PM HKT 2020] Creating domain key
[Sat Nov 28 03:20:14 PM HKT 2020] The domain key is here: /root/.acme.sh/fq.formyvmess.tk_ecc/fq.formyvmess.tk.key
[Sat Nov 28 03:20:14 PM HKT 2020] Single domain='fq.formyvmess.tk'
[Sat Nov 28 03:20:15 PM HKT 2020] Getting domain auth token for each domain
[Sat Nov 28 03:20:17 PM HKT 2020] Getting webroot for domain='fq.formyvmess.tk'
[Sat Nov 28 03:20:18 PM HKT 2020] Verifying: fq.formyvmess.tk
[Sat Nov 28 03:20:22 PM HKT 2020]fq.formyvmess.tk:Verify error:Fetching http://fq.formyvmess.tk/.well-known/acme-challenge/G6qYxcf1yidgxx3e3up2fqpiWhvqK6LsmqyqsWxwP8E: Connection refused
[Sat Nov 28 03:20:22 PM HKT 2020] Please add '--debug' or '--log' to check more details.
[Sat Nov 28 03:20:22 PM HKT 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sat Nov 28 03:20:22 PM HKT 2020] Run post hook:'mv /etc/nginx/conf/nginx.conf.bak /etc/nginx/conf/nginx.conf && sleep 2s && systemctl restart nginx'
[Sat Nov 28 03:20:26 PM HKT 2020] Lets find script dir.
[Sat Nov 28 03:20:26 PM HKT 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Sat Nov 28 03:20:26 PM HKT 2020] _script='/root/.acme.sh/acme.sh'
[Sat Nov 28 03:20:26 PM HKT 2020] _script_home='/root/.acme.sh'
[Sat Nov 28 03:20:26 PM HKT 2020] Using config home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh

**Comment by kirin10000** [comment]
```
[Sat Nov 28 03:20:22 PM HKT 2020]fq.formyvmess.tk:Verify error:Fetching http://fq.formyvmess.tk/.well-known/acme-challenge/G6qYxcf1yidgxx3e3up2fqpiWhvqK6LsmqyqsWxwP8E: Connection refused
```
这个log的意思是从公网80端口无法访问你的web服务器。
分别输入以下命令
```
cp /etc/nginx/conf/nginx.conf.default /etc/nginx/conf/nginx.conf
service nginx restart
service nginx status
wget -O- 127.0.01
wget -O- fq.formyvmess.tk
```
把日志打到这里来

**Comment by fscarmen** [comment]
root@srv17095:~# cp /etc/nginx/conf/nginx.conf.default /etc/nginx/conf/nginx.conf
cp: cannot stat '/etc/nginx/conf/nginx.conf.default': No such file or directory
root@srv17095:~# service nginx restart
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
root@srv17095:~# service nginx status
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2020-11-29 00:34:12 HKT; 26s ago
       Docs: man:nginx(8)
    Process: 3379 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Nov 29 00:34:12 srv17095 systemd[1]: Starting A high performance web server and a reverse proxy server...
Nov 29 00:34:12 srv17095 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Nov 29 00:34:12 srv17095 systemd[1]: nginx.service: Failed with result 'exit-code'.
Nov 29 00:34:12 srv17095 nginx[3379]: nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
Nov 29 00:34:12 srv17095 nginx[3379]: nginx: configuration file /etc/nginx/nginx.conf test failed
Nov 29 00:34:12 srv17095 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
root@srv17095:~# wget -O- 127.0.01
--2020-11-29 00:35:20--  http://127.0.01/
Resolving 127.0.01 (127.0.01)... 127.0.0.1
Connecting to 127.0.01 (127.0.01)|127.0.0.1|:80... failed: Connection refused.
root@srv17095:~# wget -O- fq.formyvmess.tk
--2020-11-29 00:35:37--  http://fq.formyvmess.tk/
Resolving fq.formyvmess.tk (fq.formyvmess.tk)... 2a02:180:6:1::2f61
Connecting to fq.formyvmess.tk (fq.formyvmess.tk)|2a02:180:6:1::2f61|:80... failed: Connection refused.
root@srv17095:~#

**Comment by kirin10000** [comment]
nginx貌似没有安装成功，你用的是什么系统？前面安装过程有没有报错？
