### ISSUE TITLE
安装是报错，麻烦大佬看看 centos8

### ISSUE THREAD

**Issue by jhx80kg** [kirin10000/Xray-script#40]
Last metadata expiration check: 0:00:03 ago on Sun 14 Mar 2021 09:54:51 AM CST.
No match for argument: geoip-devel
No match for argument: gperftools-devel
No match for argument: libatomic_ops-devel
Error: Unable to find a match: geoip-devel gperftools-devel libatomic_ops-devel
Error: Unknown repo: 'epel'
CentOS Linux 8 - ContinuousRelease              381  B/s | 257  B     00:00    
CentOS Linux 8 - Debuginfo                      222 kB/s |  26 MB     01:57    
CentOS Linux 8 - Devel WARNING! FOR BUILDROOT U  27 kB/s |  13 kB     00:00    
CentOS Linux 8 - FastTrack                      603  B/s | 257  B     00:00    
CentOS Linux 8 - HighAvailability               132 kB/s | 504 kB     00:03    
CentOS Linux 8 - Media - BaseOS                 0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'media-baseos':
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrom/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrom/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrecorder/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrecorder/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/CentOS/BaseOS/repodata/repomd.xml [Couldn't open file /media/CentOS/BaseOS/repodata/repomd.xml]
Error: Failed to download metadata for repo 'media-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
依赖安装失败！！

**Comment by kirin10000** [comment]
你的系统缺少epel源所以安装失败。
epel源因为几乎所有vps都会带所以脚本就没有添加。

在运行脚本前运行：
```
dnf install epel
```
即可

**Comment by elton** [comment]
好像还是不行，我安装了 epel，重启后还是报一样的错误

`# dnf install epel-release
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 2:11:46 ago on Mon Aug  2 23:21:41 2021.
Package epel-release-8-11.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!`

`Package perl-Getopt-Long-1:2.50-4.el8.noarch is already installed.
Package perl-Data-Dumper-2.167-399.el8.x86_64 is already installed.
No match for argument: libatomic_ops-devel
Error: Unable to find a match: libatomic_ops-devel
Failed to set locale, defaulting to C.UTF-8
Error: Unknown repo: 'PowerTools'
Failed to set locale, defaulting to C.UTF-8
CentOS Linux 8 - Media - BaseOS                                                         0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'media-baseos':
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrom/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrom/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/CentOS/BaseOS/repodata/repomd.xml [Couldn't open file /media/CentOS/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrecorder/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrecorder/BaseOS/repodata/repomd.xml]
Error: Failed to download metadata for repo 'media-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
依赖安装失败！！
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
按回车键继续或者Ctrl+c退出`

求帮助
