### ISSUE TITLE
你好，安装完cloudreve默认的密码是什么呢？

### ISSUE THREAD

**Issue by wimdaw** [kirin10000/Xray-script#41]
你好，安装完cloudreve默认的密码是什么呢？只有默认的账号，没有显示默认密码，请问默认密码是多少？

**Comment by kirin10000** [comment]
有显示的，可能你没注意。
选择`重置cloudreve`重置密码

**Comment by kirin10000** [comment]
请附上log，可能有Bug

**Comment by wimdaw** [comment]
我用的只有ipv6的vps，只有初始账号，没有密码显示，重置了也没有

**Comment by wimdaw** [comment]
用的euserv

**Comment by Jimmisama** [comment]
一样。重置了也没有，同样euserv```

您的选择是：20
重置Cloudreve将删除所有的Cloudreve网盘文件以及帐户信息，相当于重新安装
管理员密码忘记可以用此选项恢复
确定要继续吗？(y/n)
y

-------- 请打开"https://www.euservde.ga"进行Cloudreve初始化 -------
  1. 登陆帐号
    初始管理员账号：admin@cloudreve.org
    
  2. 右上角头像 -> 管理面板
  3. 这时会弹出对话框 "确定站点URL设置" 选择 "更改"
  4. 左侧参数设置 -> 注册与登陆 -> 不允许新用户注册 -> 往下拉点击保存



按两次回车键以继续。。。

```

**Comment by Jimmisama** [comment]
用的euserv一样没显示密码，重置也没有

**Comment by Jimmisama** [comment]
https://github.com/kirin10000/Xray-script/issues/60#issuecomment-894756872
