### ISSUE TITLE
支持禁止ip的80/443直接访问

### ISSUE THREAD

**Issue by OnlyFor** [kirin10000/Xray-script#42]
你好，首先非常感谢，脚本用起来非常非常好用，伪装网盘安全性也很高

唯一的一个问题是我在配合使用cdn的情况下不希望有暴露ip的风险

我之前的做法是简单编辑nginx给ip的443端口配个自签名证书，可以避免全网批量扫描ip的时候暴露ip对应的域名从而导致间接暴露ip

但是我发现现在vless已经占用了443端口而且不支持sni分流，我搜索了好久发现好像只能使用nginx的stream来实现，改动好像挺大的。。。

但是目前还是nginx的新手。。不太确定如何修改，只好先发个request，大佬啥时候空可以支持一下，谢谢

**Comment by kirin10000** [comment]
感谢你对脚本的认可，但是要添加这个功能难度较高且意义较低，长时间内应该都不会支持。

我推荐你还是在搭建完之后手动配置，实现你想要的功能还是可以的。
把所有域名证书都删掉，换成自签名证书，然后在Cloudflare中将`SSL/TLS 加密模式`设置为第三档：`完全`，就可以了

**Comment by OnlyFor** [comment]
感谢回复！
已经完成配置，之前以为cf不能自签名证书
