### ISSUE TITLE
请问登录cloudreve的邮箱和密码如何查看呢？

### ISSUE THREAD

**Issue by Sh1ron** [kirin10000/Xray-script#43]
设置好cloudreve需要打开页面进行登录设置，1. 登陆帐号  2. 右上角头像 -> 管理面板，请问登录cloudreve的邮箱和密码如何查看呢？

**Comment by kirin10000** [comment]
https://github.com/kirin10000/Xray-script/issues/41
你和这个是不是一样的问题？忘记密码选择重置cloudreve试试。如果没有看到初始用户名和密码则是bug，目前我还没有遇到过
