### ISSUE TITLE
xray作为前置服务器后，nginx如何获得真实IP

### ISSUE THREAD

**Issue by demonLink** [kirin10000/Xray-script#47]
目前nginx获取IP为0.0.0.0

**Comment by kirin10000** [comment]
配置proxy protocol，参考
https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-TLS-proxy%20protocol
https://xtls.github.io/config/fallback/#fallbackobject

**Comment by demonLink** [comment]
还是没有获取到，目前ip获取直接是null，附上nginx日志

`
unix: - - [22/Apr/2021:11:50:33 +0800] "GET /api/v3/site/config HTTP/2.0" 200 1906 "https://cloud.linphper.com/home?path=%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "-"
unix: - - [22/Apr/2021:11:50:33 +0800] "GET /api/v3/user/avatar/kRfO/s HTTP/2.0" 404 0 "https://cloud.linphper.com/home?path=%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "-"
unix: - - [22/Apr/2021:11:50:33 +0800] "GET /api/v3/user/storage HTTP/2.0" 200 75 "https://cloud.linphper.com/home?path=%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "-"
unix: - - [22/Apr/2021:11:50:33 +0800] "GET /api/v3/directory%2F HTTP/2.0" 200 58 "https://cloud.linphper.com/home?path=%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "-"
unix: - - [22/Apr/2021:11:50:33 +0800] "GET /api/v3/user/storage HTTP/2.0" 200 75 "https://cloud.linphper.com/home?path=%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "-"
unix: - - [22/Apr/2021:11:50:33 +0800] "GET /favicon.ico HTTP/2.0" 200 1962 "https://cloud.linphper.com/home?path=%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "-"
unix: - - [22/Apr/2021:11:50:33 +0800] "GET /manifest.json HTTP/2.0" 200 213 "https://cloud.linphper.com/home?path=%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "-"
unix: - - [22/Apr/2021:11:50:34 +0800] "GET /manifest.json HTTP/2.0" 200 213 "https://cloud.linphper.com/home?path=%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "-"
unix: - - [22/Apr/2021:11:50:35 +0800] "GET /service-worker.js HTTP/2.0" 304 0 "https://cloud.linphper.com/service-worker.js" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "-"
`

部分xray服务端配置
`    "inbounds": [
        {
            "listen":"0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": xxxxxxxxxxxxxxxxxxxx",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "path": "/d45e16c",
                        "dest": "@/dev/shm/xray/ws.sock",
                        "xver": 1
                    },
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/nginx_unixsocket/h2.sock",
                        "xver": 1
                    },
                    {
                        "dest": "/dev/shm/nginx_unixsocket/default.sock",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/nginx/certs/linphper.com.cer",
                            "keyFile": "/usr/local/nginx/certs/linphper.com.key",
                            "ocspStapling": 3600,
                            "oneTimeLoading": true
                        },
                        {
                            "certificateFile": "/usr/local/nginx/certs/cloud.linphper.com.cer",
                            "keyFile": "/usr/local/nginx/certs/cloud.linphper.com.key",
                            "ocspStapling": 3600,
                            "oneTimeLoading": true
                        }
                    ]
                }
            }
        },
`

xray配置
`server {
    listen unix:/dev/shm/nginx_unixsocket/default.sock proxy_protocol;
    listen unix:/dev/shm/nginx_unixsocket/h2.sock http2 proxy_protocol;
    server_name cloud.linphper.com;
    set_real_ip_from 127.0.0.1;
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
    location / {
        proxy_set_header X-Forwarded-For 127.0.0.1;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://unix:/dev/shm/cloudreve_unixsocket/cloudreve.sock;
        client_max_body_size 0;
    }
}
`
nginx配置
`http {
    include       mime.types;
    default_type  application/octet-stream;

    index    index.html index.htm;

    proxy_set_header X-Real-IP       $proxy_protocol_addr;
    proxy_set_header X-Forwarded-For $proxy_protocol_addr;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;
}`

**Comment by kirin10000** [comment]
`$proxy_protocol_addr`记录了真实ip，需要把他写进log里

**Comment by demonLink** [comment]
> `$proxy_protocol_addr`记录了真实ip，需要把他写进log里

好的，解决！！谢谢！
