### ISSUE TITLE
一键脚本构建的nextcloud网站，用firefox不能访问

### ISSUE THREAD

**Issue by tefiszx** [kirin10000/Xray-script#48]
firefox提示网站的tls证书为自签名证书，不接受其安全性。然而用chrome却可以访问。
请问作者要如何排查？

firefox的错误代码是：
错误代码：MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

**Comment by sportfit** [comment]
之前脚本安装多次，均无此现象，现在无论构建哪个伪装网站，均遇到同样问题。使用Firefox浏览器很久，略知一二，它默认对所有的SSL\TLS保护的站点开启OCSP在线状态校验，确保证书真实有效。解决：服务器上开启ocsp装订或关闭firefox的ocsp check，因此我选择关闭了firefox的ocsp强制校验，证书还是有效的，于是通过。

**Comment by tefiszx** [comment]
> 之前脚本安装多次，均无此现象，现在无论构建哪个伪装网站，均遇到同样问题。使用Firefox浏览器很久，略知一二，它默认对所有的SSL\TLS保护的站点开启OCSP在线状态校验，确保证书真实有效。解决：服务器上开启ocsp装订或关闭firefox的ocsp check，因此我选择关闭了firefox的ocsp强制校验，证书还是有效的，于是通过。

谢谢你的提醒。
