### ISSUE TITLE
debian10 找不到sysctl

### ISSUE THREAD

**Issue by delphinuz** [kirin10000/Xray-script#5]
因为PATH没有/sbin。也許可以在script裡的PATH加入。

**Comment by kirin10000** [comment]
是 deian10 找不到sysctl还是 你的debian10 找不到sysctl ，这点还有待考证。因为目前还没有出现其它debian10找不到sysctl的情况。基本上每台vps的的debian10都不是原版的debian10，服务器提供商会对原版系统进行微改。
关于sysctl问题我会以原版debian10为准

**Comment by kirin10000** [comment]
debian10 标准系统没有sysctl问题

**Comment by delphinuz** [comment]
理解。是我系統提供的debian10，环境PATH不包括 /sbin。
