### ISSUE TITLE
请求加入自定义入站端口选项

### ISSUE THREAD

**Issue by AexChan** [kirin10000/Xray-script#50]
我正在使用流量转发服务。
现在，大部分的服务提供商已经不再允许转发端口为80/443/8080/8443等端口。
而脚本默认入站端口为443且无法在脚本中进行更改，故请求加入自定义入站端口选项。
感谢开发者的无私贡献！

**Comment by kirin10000** [comment]
你可以自己修改xray配置的端口。
脚本不会添加这个功能，原因：非443端口特征太明显

**Comment by feiyue789** [comment]
443端口最近被封了好多，希望可以支持在脚步里面自定义端口，照顾一下小白
