### ISSUE TITLE
line 3558: =0: command not found

### ISSUE THREAD

**Issue by GWONGJYULEI** [kirin10000/Xray-script#52]
脚本版本：21:50前的最新版本

当脚本运行完后，报错如下：

> ./Xray-TLS+Web-setup.sh: line 3558: =0: command not found

当退出脚本后，报错如下：

> ./Xray-TLS+Web-setup.sh: line 3560: syntax error near unexpected token `fi'

> ./Xray-TLS+Web-setup.sh: line 3560: `fi'

**Comment by kirin10000** [comment]
脚本最近一次更新是5月26日 17：52

> 脚本版本：21:50前的最新版本
> 
这个时间是5月26日 21：50


也就是最新的脚本。

可是最新的脚本只有3557行呀
![image](https://user-images.githubusercontent.com/57820613/119769976-1b08fd80-beee-11eb-8f06-4ab8df63c92e.png)

何来3558 3560报错

**Comment by kirin10000** [comment]
此问题可以被复现。可能是脚本太大了没有一次性加载入内存再开始执行。找时间修复
