### ISSUE TITLE
火狐浏览器打不开网页，chrome能打开网页

### ISSUE THREAD

**Issue by j19981106** [kirin10000/Xray-script#53]
Debian系统下用脚本安装好后，Firefox浏览器打不开脚本搭建的网页，chrome能打开脚本搭建的网页，暂时没有找到原因。

![图片](https://user-images.githubusercontent.com/74053663/120125344-f0b78880-c1ea-11eb-9706-22b2dfaecc8e.png)

**Comment by kirin10000** [comment]
这是由于服务器没有提供ocsp staple没有生效导致的。脚本申请的证书为ocsp must staple，如果服务器没有进行ocsp staple，firefox就会报错。

在这里，ocsp staple是由xray服务端提供的，脚本已经正确配置了ocsp staple，如果依然出现这个问题，可能有两个原因：
1. 服务端ocsp还准备好，解决方法：等一会儿，多刷新几次。
2. 服务端没有提供ocsp，解决方法：在xray-core开issue，提交bug，等待修复

**Comment by j19981106** [comment]
https://github.com/XTLS/Xray-core/issues/578#issuecomment-851718728

**Comment by j19981106** [comment]
> 
> 
> 这是由于服务器没有提供`ocsp staple`导致的。脚本申请的证书为ocsp must staple，如果服务器没有提供`ocsp staple`，firefox就会报错。
> 
> 在这里，`ocsp staple`是由xray服务端提供的，脚本已经正确配置了`ocsp staple`，如果依然出现这个问题，可能有两个原因：
> 
>     1. 服务端`ocsp staple`还准备好，解决方法：等一会儿，多刷新几次。
> 
>     2. 服务端没有正确提供`ocsp staple`的功能，解决方法：在xray-core开issue，提交bug，等待修复

https://github.com/XTLS/Xray-core/issues/578#issuecomment-851718728

**Comment by kirin10000** [comment]
脚本已经临时修改了

**Comment by j19981106** [comment]
> 
> 
> 脚本已经临时修改了

看到了，我想问一下这个 `OneTimeLoading` 是什么，有什么作用

**Comment by kirin10000** [comment]
> 看到了，我想问一下这个 `OneTimeLoading` 是什么，有什么作用

关闭域名证书的热重载功能（Xray-core有域名证书热重载的功能，即更新域名证书文件后不需要重启Xray就能生效）
