### ISSUE TITLE
ARM服务器假full cone问题

### ISSUE THREAD

**Issue by steamch** [kirin10000/Xray-script#56]
你好，最近在ARM服务器上使用了脚本安装XRAY
在nat测试的时候发现
filtering behavior那一栏显示的是AddressAndPortDependent
正常的full cone会显示EndpointIndependent
服务器端口已全开
-----------------------------------------------------------------------
系统是ubuntu 20.04
测试工具是https://github.com/HMBSbige/NatTypeTester
在X86服务器搭建的XRAY测试正常
-----------------------------------------------------------------------
请教一下这是什么原因，如需要log还请告诉我这个log文件正常在什么位置里或者叫什么名字。我没找到

**Comment by kirin10000** [comment]
我最近没有时间，你可以试试去xray-core问问

**Comment by steamch** [comment]
> 我最近没有时间，你可以试试去xray-core问问

好的
