### ISSUE TITLE
脚本中acme.sh申请证书失败

### ISSUE THREAD

**Issue by zoumeng** [kirin10000/Xray-script#58]
[Tue 15 Jun 2021 06:09:58 AM UTC] Le_LocalAddress
[Tue 15 Jun 2021 06:09:58 AM UTC] d='www.xxx.best'
[Tue 15 Jun 2021 06:09:58 AM UTC] Check for domain='www.xxx.best'
[Tue 15 Jun 2021 06:09:58 AM UTC] _currentRoot='/usr/local/nginx/html/issue_certs'
[Tue 15 Jun 2021 06:09:58 AM UTC] d
[Tue 15 Jun 2021 06:09:58 AM UTC] config file is empty, can not read CA_KEY_HASH
[Tue 15 Jun 2021 06:09:58 AM UTC] Using config home:/root/.acme.sh
[Tue 15 Jun 2021 06:09:58 AM UTC] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Tue 15 Jun 2021 06:09:58 AM UTC] _init api for server: https://acme.zerossl.com/v2/DV90
[Tue 15 Jun 2021 06:09:58 AM UTC] EC key
[Tue 15 Jun 2021 06:09:58 AM UTC] config file is empty, can not read CA_EAB_KEY_ID
[Tue 15 Jun 2021 06:09:58 AM UTC] config file is empty, can not read CA_EAB_HMAC_KEY
[Tue 15 Jun 2021 06:09:58 AM UTC] config file is empty, can not read CA_EMAIL
[Tue 15 Jun 2021 06:09:58 AM UTC] No EAB credentials found for ZeroSSL, let's get one
[Tue 15 Jun 2021 06:09:58 AM UTC] acme.sh is using ZeroSSL as default CA now.
[Tue 15 Jun 2021 06:09:58 AM UTC] Please update your account with an email address first.
[Tue 15 Jun 2021 06:09:58 AM UTC] acme.sh --register-account -m my@example.com
[Tue 15 Jun 2021 06:09:58 AM UTC] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
[Tue 15 Jun 2021 06:09:58 AM UTC] _on_issue_err
[Tue 15 Jun 2021 06:09:58 AM UTC] Please add '--debug' or '--log' to check more details.
[Tue 15 Jun 2021 06:09:58 AM UTC] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Tue 15 Jun 2021 06:09:58 AM UTC] Run post hook:'mv /usr/local/nginx/conf/nginx.conf.bak /usr/local/nginx/conf/nginx.conf && sleep 2s && systemctl restart nginx'
[Tue 15 Jun 2021 06:10:00 AM UTC] Diagnosis versions: 

     测试环境Ubuntu20.04，申请失败的原因是acme.sh更换了颁发证书的网站从letsencrypt改为ZeroSSL。申请参数改了ZeroSSL申请证书需要提交“--register-account -m my@example.com”。脚本失败的提示信息是config file is empty, can not read CA_EAB_KEY_ID, config file is empty, can not read CA_EAB_HMAC_KEY, config file is empty, can not read CA_EMAIL。

     ~/.acme.sh/account.conf文件中有ACCOUNT_EMAIL='xxx@xxx.com'这行给参数应该可以正常申请证书。

**Comment by ThuSNO3** [comment]
Ubuntu20.04 同样的问题

**Comment by zoumeng** [comment]
acme.sh官方文档在安装acme.sh时需要指定mail address

2. Or, Install from git
Clone this project and launch installation:

git clone https://github.com/acmesh-official/acme.sh.git
cd ./acme.sh
./acme.sh --install -m my@example.com

**Comment by kirin10000** [comment]
@zoumeng @ThuSNO3 选择重置域名/重新安装 以修复

**Comment by ThuSNO3** [comment]
> @zoumeng @ThuSNO3 选择重置域名/重新安装 以修复

解决了，谢谢
