### ISSUE TITLE
【提问】请问如何指定所用的加密套件？

### ISSUE THREAD

**Issue by GWONGJYULEI** [kirin10000/Xray-script#59]
现在默认情况下，使用的是 AES-128-GCM，希望能指定为 CHACHA20-POLY1305

感谢作者的无私奉献！

**Comment by kirin10000** [comment]
在`/usr/local/etc/xray/config.json`里面指定

**Comment by GWONGJYULEI** [comment]
感谢回复！我已经将配置修改成如下：
```
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.3",
                    "cipherSuites": "TLS_CHACHA20_POLY1305_SHA256",
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/nginx/certs/xxx.cer",
                            "keyFile": "/usr/local/nginx/certs/xxx.key",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
```
但仍然是使用 AES-128-GCM 套件。
请问这种情况，又应该怎么解决呢？

**Comment by kirin10000** [comment]
命名方式不一样。相同的加密套件在go程序里和openssl(nginx)里的名字方式不一样，具体你可以取xray-core那边问

**Comment by GWONGJYULEI** [comment]
以下引用自 Golang 的加密套件的名词和说明：

[https://golang.org/src/crypto/tls/cipher_suites.go#L500](https://golang.org/src/crypto/tls/cipher_suites.go#L500)
> // TLS 1.3 cipher suites.
> 	TLS_CHACHA20_POLY1305_SHA256 uint16 = 0x1303
> ...

[https://golang.org/src/crypto/tls/cipher_suites.go#L44](https://golang.org/src/crypto/tls/cipher_suites.go#L44)
> {TLS_CHACHA20_POLY1305_SHA256, "TLS_CHACHA20_POLY1305_SHA256", supportedOnlyTLS13, false},

以下引用自 OpenSSL：

> root@localhost:~# openssl ciphers
> TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256
> ...

能说明 Golang 和 OpenSSL 对 CHACHA20 套件的命名是一样的吗？

**Comment by kirin10000** [comment]
`openssl ciphers -v`查看，`TLS_CHACHA20_POLY1305_SHA256`是TLS 1.3的加密套件。TLS 1.3的加密套件不受控制，只能选择开启/关闭TLS 1.3

**Comment by kirin10000** [comment]
脚本里的那几个指定加密套件都是TLS 1.2的

**Comment by GWONGJYULEI** [comment]
在 xray 配置文件中指定了 TLS 的最高版本为 1.2 后，成功使用指定的加密套件，谢谢大佬
