### ISSUE TITLE
有考虑让xray使用port 443入站吗？

### ISSUE THREAD

**Issue by delphinuz** [kirin10000/Xray-script#6]
不知为何，大多数的script都是nginx入站，再转发到xray(or v2ray)，这样不是效率比较低？

是否直接使用xray(vless+xtls)入站，再fallback到trojain再到nginx，或ws(vless+ws)?

另外使用xray才是主要目地，nginx是陪衬，应没必要重新编译nginx?只要能跑就行了？

**Comment by kirin10000** [comment]
我的脚本不就是xray 443入站吗？nginx就是陪衬。

关于为什么编译nginx的问题，主要是为了方便管理。
祥见 https://github.com/kirin10000/Xray-script#安装时长说明

**Comment by delphinuz** [comment]
也许安裝nginx前可以多个选择，可自行编译或直接安装.deb。
