### ISSUE TITLE
磨難試真金，請求增加非443 端口

### ISSUE THREAD

**Issue by PS0123456** [kirin10000/Xray-script#62]
特殊的日子，今天443端口都被封了，也查詢到曾經有人提過這個增加端口的需求。
結合今天的情況，還請大佬再考慮下，至少給個選項做個備胎吧。不然向今天這樣，很多人束手無策，除了開CDN

**Comment by PS0123456** [comment]
不一定非要走TLS，其他端口vmless+tcp還不一定被封

**Comment by kilolumen** [comment]
同求

**Comment by luckiestone** [comment]
遇到同样的问题，去重置了IP，顺便问下，更换IP后需要重新配置脚本吗

**Comment by kursk-ye** [comment]
同求

**Comment by GWONGJYULEI** [comment]
除了重置IP，还可以用该脚本重新安装一个“3合1”的配置（TCP/GRPC/WS）。我换了WS，再套个CDN，就复活了，等风头过了，就关掉CND，用回TCP

**Comment by kirin10000** [comment]
> 遇到同样的问题，去重置了IP，顺便问下，更换IP后需要重新配置脚本吗

不需要

**Comment by kirin10000** [comment]
运行以下命令可以临时修改端口：
```bash
sed -i 's/"port": 443,/"port": 你的端口号,/g' /usr/local/etc/xray/config.json
systemctl restart xray
```
@kursk-ye @kilolumen @PS0123456 @luckiestone

**Comment by PS0123456** [comment]
> 运行以下命令可以临时修改端口：
> 
> ```shell
> sed -i 's/"port": 443,/"port": 你的端口号,/g' /usr/local/etc/xray/config.json
> systemctl restart xray
> ```
> 
> @kursk-ye @kilolumen @PS0123456 @luckiestone

THX
