### ISSUE TITLE
脚本自带的BBR安装，安装原版BBR失败

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [kirin10000/Xray-script#64]
![image](https://user-images.githubusercontent.com/38343280/125887918-61a7c867-ae49-4ce9-8401-def202f32ff9.png)
5.13版时安装正常，5.13.1开始到现在5.13.2都一直失败，xanmod内核则安装正常

**Comment by kirin10000** [comment]
@ShoukakuChuuCC  感谢反馈

**Comment by ShoukakuChuuCC** [comment]
![image](https://user-images.githubusercontent.com/38343280/125906501-9944f5b0-1ca4-45ae-a594-470d8883dbbe.png)
fix后debian10.10安装原版BBR失败

**Comment by ShoukakuChuuCC** [comment]
> @ShoukakuChuuCC 感谢反馈

![image](https://user-images.githubusercontent.com/38343280/125906557-b6a37fe5-1950-47fd-9154-f937d1cc54ad.png)
fix后debian10.10安装原版BBR失败

**Comment by kirin10000** [comment]
是的，`debian 10.10`已经不支持了。
你可以试试ubuntu

**Comment by kirin10000** [comment]
@ShoukakuChuuCC
