### ISSUE TITLE
oracle主机无法申请证书

### ISSUE THREAD

**Issue by 4860575** [kirin10000/Xray-script#65]
环境：oracle
系统：ubuntu20
问题：无法申请证书，使用mack-a的脚本可以正常申请

**Comment by kirin10000** [comment]
抱歉，无法复现，有log吗？

**Comment by Jimmisama** [comment]
我解决了，方法简单粗暴直接彻底干掉防火墙。控制台先开放全部端口[链接](https://www.coldawn.com/%E7%94%B2%E9%AA%A8%E6%96%87oracle-cloud%E5%85%8D%E8%B4%B9vps-ubuntu-18-04-20-04-%E7%B3%BB%E7%BB%9F%E9%98%B2%E7%81%AB%E5%A2%99%EF%BC%88ufw%E5%92%8Ciptables%EF%BC%89%E7%9A%84%E6%AD%A3%E7%A1%AE%E9%85%8D/)
