### ISSUE TITLE
CentOS 8 安装失败

### ISSUE THREAD

**Issue by elton** [kirin10000/Xray-script#66]
CentOS 8，总是提示安装依赖失败。
`Last metadata expiration check: 2:10:03 ago on Mon Aug  2 23:21:41 2021.
Package perl-Getopt-Long-1:2.50-4.el8.noarch is already installed.
Package perl-Data-Dumper-2.167-399.el8.x86_64 is already installed.
No match for argument: libatomic_ops-devel
Error: Unable to find a match: libatomic_ops-devel
Failed to set locale, defaulting to C.UTF-8
Error: Unknown repo: 'PowerTools'
Failed to set locale, defaulting to C.UTF-8
CentOS Linux 8 - Media - BaseOS                                                         0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'media-baseos':
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrom/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrom/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/CentOS/BaseOS/repodata/repomd.xml [Couldn't open file /media/CentOS/BaseOS/repodata/repomd.xml]
  - Curl error (37): Couldn't read a file:// file for file:///media/cdrecorder/BaseOS/repodata/repomd.xml [Couldn't open file /media/cdrecorder/BaseOS/repodata/repomd.xml]
Error: Failed to download metadata for repo 'media-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
依赖安装失败！！
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
按回车键继续或者Ctrl+c退出`

epel源也装了
# dnf install epel-release
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 2:11:46 ago on Mon Aug  2 23:21:41 2021.
Package epel-release-8-11.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!

VPS 在北美，bwg 的 加州节点

**Comment by kirin10000** [comment]
感谢反馈，已尝试修复，请再次尝试
