### ISSUE TITLE
VLESS+XTLS没有下行流量

### ISSUE THREAD

**Issue by CryFrogg** [kirin10000/Xray-script#69]
本人在一个纯净Ubuntu服务器安装了TCP+Websocket，成功配置了VLESS+XTLS 和 VLESS+WS+TLS。
全部都显示安装成功，期间也没有报错。
但在使用客户端Qv2ray导入设置后，VLESS+XTLS没有任何下行流量，端口配置都是正确的。也就是说我的浏览器可以正常发送请求，但是接收不到回复。
反观VLESS+WS+TLS则没有任何问题。

想请问一下可能原因是什么呢?

**Comment by kirin10000** [comment]
多半是你客户端没有配置正确。或者你的vps被封了然后websocket走的是cdn

**Comment by CryFrogg** [comment]
我试了一下安卓端v2rayNG是可以正常连接的，应该是windows的Qv2ray客户端有问题，感谢回答！
