### ISSUE TITLE
xtls过几天就不能用了，什么问题

### ISSUE THREAD

**Issue by feiyue789** [kirin10000/Xray-script#7]
刚开始能用，过了几天就连不上了，ws+tls就没问题。上一次也是这样，重装之后xtls就能用，今天又不行了，提示这个net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x01\x00\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01

**Comment by kirin10000** [comment]
@feiyue789 你是不是开启了cdn，然后xtls配置下服务器一栏填的是域名？

**Comment by feiyue789** [comment]
> @feiyue789 你是不是开启了cdn，然后xtls配置下服务器一栏填的是域名？

开启cdn的话服务器地址填ip可以正常用xtls吗

**Comment by kirin10000** [comment]
> > @feiyue789 你是不是开启了cdn，然后xtls配置下服务器一栏填的是域名？
> 
> 开启cdn的话服务器地址填ip可以正常用xtls吗

@feiyue789 可以

**Comment by feiyue789** [comment]
> > > @feiyue789 你是不是开启了cdn，然后xtls配置下服务器一栏填的是域名？
> > 
> > 
> > 开启cdn的话服务器地址填ip可以正常用xtls吗
> 
> @feiyue789 可以

大佬能整个流量统计吗，腾讯云这种流量用了多少都看不出来，延迟太久了
