### ISSUE TITLE
sleep and  Retry after 15 sec

### ISSUE THREAD

**Issue by libea18** [kirin10000/Xray-script#70]
i see this : 
[Sat Aug 14 17:26:02 UTC 2021] Order status is processing, lets sleep and retry.
[Sat Aug 14 17:26:02 UTC 2021] Retry after: 15

i wanna reduce 15 sec to 2-3 sec 
How can I do that? Where should the source and script change? Can you help?

**Comment by libea18** [comment]
I see https://github.com/kirin10000/Xray-script/blob/b0aa253db44f59d29f77dd720ac0a63c8cdc43e9/Xray-TLS٪2BWeb-setup.sh#L346 and change it to 3s but it does not apply in installation

**Comment by kirin10000** [comment]
this is normal, sleep 15s is from acme.sh https://github.com/acmesh-official/acme.sh

**Comment by libea18** [comment]
Could we decrease this?😑

**Comment by kirin10000** [comment]
You can try to ask acme.sh official. For me 15s is not long
