### ISSUE TITLE
Debian 10.10/11 运行脚本时多处出现问题：

### ISSUE THREAD

**Issue by Lostsite** [kirin10000/Xray-script#74]
1. 选择
 “------------------请选择要使用的bbr版本------------------
  1. 安装/升级最新稳定版内核并启用bbr  (推荐)”
  时报错 ：
“当前系统版本过低，不支持安装此内核！
请使用新系统或选择安装xanmod内核“

2. 选择搭建Nextcloud时，卡住在 ”make: *** [Makefile:900: ext/fileinfo/libmagic/apprentice.lo] Error 1”
（已开Swap file， 总内存3G （1+2））

**Comment by kirin10000** [comment]
有没有更完整的log

**Comment by kirin10000** [comment]
如果最后是提示`killed`或`已杀死`说明是内存不足，否则是其它原因

**Comment by kirin10000** [comment]
debian11无法复现

**Comment by limetw** [comment]
OpenVZ吧
