### ISSUE TITLE
可以跟宝塔面板兼容一下吗?  感谢你的付出

### ISSUE THREAD

**Issue by ialee9** [kirin10000/Xray-script#76]
可以跟宝塔面板兼容一下吗?  这个应该是许多的小白想要的.

或者可以提示一下怎么修改. 感谢

ps. 你的脚本我试过, 是最快最稳定.. 实在是太感谢.

有你我们这些小白就太轻松了

**Comment by kirin10000** [comment]
感谢您对的认可
但这个兼容比较困难，因为宝塔本身是一个完整的系统，并不是一个模块或者一个功能。至少短期内是不会去做的
