### ISSUE TITLE
vless进站的id与ws里的不同

### ISSUE THREAD

**Issue by delphinuz** [kirin10000/Xray-script#8]
不是应同样的uuid吗？但自动配置的config.json里面二个uuid是不同的。

这样对client来说，是用前者或后者？按理vless进站应用vless的uuid，但script最后显示的配置是ws的uuid。

更新：刚想了一下，不同的uuid是为了vless+xtls与vless+tls+ws分开始用？不过显示的配置只有一种。

**Comment by kirin10000** [comment]
显示的配置有两种，往上拉。如果只看到一种，可能是被shell，截掉了，已知谷歌云webshell就有这种情况
