### ISSUE TITLE
Debian10 安装依赖失败   获取BBR最新内核版本error

### ISSUE THREAD

**Issue by nvgt610** [kirin10000/Xray-script#84]
Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64
脚本为最新发行版本

------------------------ Xray-TLS+Web 搭建/管理脚本 ------------------------

           Xray   ：           未安装                未运行

           Nginx  ：           未安装                未运行

           php    ：           未安装                未运行

        Cloudreve ：           未安装                未运行

       官网：https://github.com/kirin10000/Xray-script

----------------------------------注意事项----------------------------------
 1. 此脚本需要一个解析到本服务器的域名
 2. 此脚本安装时间较长，建议在安装前阅读：
      https://github.com/kirin10000/Xray-script#安装时长说明
 3. 建议在纯净的系统上使用此脚本 (VPS控制台-重置系统)
----------------------------------------------------------------------------

 -----------安装/更新/卸载-----------
   1. 安装Xray-TLS+Web
         流程：[更新系统组件]->[安装bbr]->[安装php]->安装Nginx->安装Xray->申请证书->配置文件->[安装/配置Cloudreve]
   2. 更新Xray-TLS+Web
         流程：更新脚本->[更新系统组件]->[更新bbr]->[更新php]->[更新Nginx]->更新Xray->更新证书->更新配置文件->[更新Cloudreve]
   3. 检查更新/更新脚本
   4. 更新系统组件
   5. 安装/检查更新/更新bbr
         包含：bbr2/bbrplus/bbr魔改版/暴力bbr魔改版/锐速
   6. 安装/检查更新/更新php
   7. 检查更新/更新Nginx
   8. 更新Cloudreve
   9. 更新Xray
  10. 卸载Xray-TLS+Web
  11. 卸载php
  12. 卸载Cloudreve

 --------------启动/停止-------------
  13. 启动/重启Xray-TLS+Web
  14. 停止Xray-TLS+Web

 ----------------管理----------------
  15. 查看配置信息
  16. 重置域名
         将删除所有域名配置，安装过程中域名输错了造成Xray无法启动可以用此选项修复
  17. 添加域名
  18. 删除域名
  19. 修改伪装网站类型
  20. 重新安装Cloudreve
         将删除所有Cloudreve网盘的文件和帐户信息，管理员密码忘记可用此选项恢复
  21. 修改传输协议
  22. 修改id(用户ID/UUID)
  23. 修改gRPC的serviceName
  24. 修改WebSocket的path(路径)

 ----------------其它----------------
  25. 精简系统
         删除不必要的系统组件，即使已经安装 Xray-TLS+Web 仍然可以使用此功能
  26. 尝试修复退格键无法使用的问题
         部分ssh工具(如Xshell)可能有这类问题
  27. 修改dns
  0. 退出脚本

您的选择是：1
正在检查端口占用。。。
--2021-11-03 08:30:45--  https://github.com/kirin10000/Xray-script/raw/main/Xray-TLS+Web-setup.sh
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kirin10000/Xray-script/main/Xray-TLS%2BWeb-setup.sh [following]
--2021-11-03 08:30:45--  https://raw.githubusercontent.com/kirin10000/Xray-script/main/Xray-TLS%2BWeb-setup.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 163735 (160K) [text/plain]
Saving to: ‘STDOUT’

-                                               100%[====================================================================================================>] 159.90K  --.-KB/s    in 0.01s

2021-11-03 08:30:45 (13.5 MB/s) - written to stdout [163735/163735]

脚本已经是最新版本

------------------------------------------
 安装可能需要比较长的时间
 如果中途断开连接将会很麻烦
 设置ssh连接超时时间将有效降低断连可能性

是否设置ssh连接超时时间？(y/n)
n
正在删除防火墙。。。
Xray-TLS+Web-setup.sh: line 775: ufw: command not found
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'firewalld' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'ufw' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Failed to stop firewalld.service: Unit firewalld.service not loaded.
Failed to disable unit: Unit file firewalld.service does not exist.
正在删除阿里云盾和腾讯云盾 (仅对阿里云和腾讯云服务器有效)。。。
Failed to stop CmsGoAgent.service: Unit CmsGoAgent.service not loaded.
Failed to disable unit: Unit file CmsGoAgent.service does not exist.
Failed to stop cloudmonitor.service: Unit cloudmonitor.service not loaded.
Xray-TLS+Web-setup.sh: line 788: /etc/rc.d/init.d/cloudmonitor: No such file or directory
Failed to stop AssistDaemon.service: Unit AssistDaemon.service not loaded.
Failed to disable unit: Unit file AssistDaemon.service does not exist.
Failed to stop aliyun.service: Unit aliyun.service not loaded.
Failed to disable unit: Unit file aliyun.service does not exist.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package aliyun-assist
Xray-TLS+Web-setup.sh: line 810: /etc/init.d/aegis: No such file or directory
Xray-TLS+Web-setup.sh: line 819: /usr/local/qcloud/stargate/admin/uninstall.sh: No such file or directory
Xray-TLS+Web-setup.sh: line 820: /usr/local/qcloud/YunJing/uninst.sh: No such file or directory
Xray-TLS+Web-setup.sh: line 821: /usr/local/qcloud/monitor/barad/admin/uninstall.sh: No such file or directory
Failed to stop YDService.service: Unit YDService.service not loaded.
Failed to disable unit: Unit file YDService.service does not exist.
Failed to stop tat_agent.service: Unit tat_agent.service not loaded.
Failed to disable unit: Unit file tat_agent.service does not exist.
Xray-TLS+Web-setup.sh: line 842: kill: `': not a pid or valid job spec

-----------------------是否更新系统组件？-----------------------
 1. 更新已安装软件，并升级系统 (Ubuntu专享)
 2. 仅更新已安装软件
 3. 不更新

您的选择是：2
-----------------------即将开始更新-----------------------
 更新过程中遇到问话/对话框，如果不明白，选择yes/y/第一个选项
 按回车键继续。。。
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.4' to '10.11'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
Reading package lists... Done
E: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease
E: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease
E: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  linux-image-4.19.0-9-amd64
The following packages will be upgraded:
  linux-image-amd64
1 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 48.2 MB of archives.
After this operation, 269 MB of additional disk space will be used.
Get:1 http://security.debian.org/debian-security buster/updates/main amd64 linux-image-4.19.0-9-amd64 amd64 4.19.118-2+deb10u1 [48.2 MB]
Err:2 http://deb.debian.org/debian buster/main amd64 linux-image-amd64 amd64 4.19+105+deb10u4
  404  Not Found [IP: 2a04:4e42:6::644 80]
Fetched 48.2 MB in 4s (11.3 MB/s)
E: Failed to fetch http://deb.debian.org/debian/pool/main/l/linux-latest/linux-image-amd64_4.19+105+deb10u4_amd64.deb  404  Not Found [IP: 2a04:4e42:6::644 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
正在获取最新版本内核版本号。。。。(60内秒未获取成功自动跳过)

------------------请选择要使用的bbr版本------------------
  1. 安装/升级最新稳定版内核并启用bbr  (推荐)
  2. 安装/升级最新xanmod内核并启用bbr  (推荐)
  3. 安装/升级最新xanmod内核并启用bbr2 (推荐)
  4. 安装/升级最新版内核并启用bbr
  5. 启用bbr
  6. 启用bbr2
  7. 安装第三方内核并启用bbrplus/bbr魔改版/暴力bbr魔改版/锐速
  8. 更换队列算法
  9. 开启/关闭bbr2_ECN
 10. 卸载多余内核
  0. 退出bbr安装
------------------关于安装bbr加速的说明------------------
 bbr拥塞算法可以大幅提升网络速度，建议启用
 更换第三方内核可能造成系统不稳定，甚至无法开机
---------------------------------------------------------
 当前内核版本：4.19
 最新内核版本：error
 当前内核是否支持bbr：
     是
   当前拥塞控制算法：
       bbr
   当前队列算法：
       fq
   当前bbr2_ECN：
       未启用

您的选择是：0
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

---------------------请选择传输层协议---------------------
 1. TCP
 2. gRPC
 3. WebSocket
 4. TCP + gRPC
 5. TCP + WebSocket
 6. gRPC + WebSocket
 7. TCP + gRPC + WebSocket
 0. 无 (仅提供Web服务)

 注：
   1. 不知道什么是CDN或不使用CDN，请选择TCP
   2. gRPC和WebSocket支持通过CDN，关于两者的区别，详见：https://github.com/kirin10000/Xray-script#关于grpc与websocket
   3. 只有TCP能使用XTLS，且XTLS完全兼容TLS
   4. 能使用TCP传输的只有VLESS

您的选择是：1

--------------------请选择域名解析情况--------------------
 1. 主域名 和 www.主域名 都解析到此服务器上 (推荐)
    如：123.com 和 www.123.com 都解析到此服务器上
 2. 仅某个特定域名解析到此服务器上
    如：123.com 或 www.123.com 或 xxx.123.com 中的一个解析到此服务器上

您的选择是：2

-------请输入解析到此服务器的域名(前面不带"http://"或"https://")-------
请输入域名：ww.xxx.com

您输入的域名是"www.xxx.com"，确认吗？(y/n)
y

------------------------------请选择伪装网站页面------------------------------
 1. Cloudreve (推荐)
     个人网盘
 2. Nextcloud (推荐)
     个人网盘，需安装php
 3. 403页面
     模拟网站后台
 4. 自定义静态网站 (不推荐)
 5. 自定义反向代理网页 (不推荐)

 内存<128MB 建议选择 403页面
 128MB<=内存<1G 建议选择 Cloudreve
 内存>=1G 建议选择 Nextcloud 或 Cloudreve

 关于选择伪装网站的详细说明见：https://github.com/kirin10000/Xray-script#伪装网站说明

您的选择是：3
即将开始安装Xray-TLS+Web，可能需要10-20分钟。。。
正在安装Nginx编译工具链。。。
Reading package lists... Done
Building dependency tree
Reading state information... Done
gzip is already the newest version (1.9-3).
perl is already the newest version (5.28.1-6).
perl-base is already the newest version (5.28.1-6).
tar is already the newest version (1.30+dfsg-6).
wget is already the newest version (1.20.1-1.1).
ca-certificates is already the newest version (20200601~deb10u1).
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-8 g++-8 gcc-8 libasan5 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libgcc-8-dev libgomp1 libisl19 libitm1 liblsan0
  libmpc3 libmpfr6 libmpx2 libquadmath0 libstdc++-8-dev libtsan0 libubsan1 linux-libc-dev
Suggested packages:
  binutils-doc cpp-doc gcc-8-locales g++-multilib g++-8-multilib gcc-8-doc libstdc++6-8-dbg gcc-multilib manpages-dev autoconf automake libtool flex bison gdb gcc-doc gcc-8-multilib
  libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg libmpx2-dbg libquadmath0-dbg glibc-doc libstdc++-8-doc make-doc
Recommended packages:
  manpages-dev
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-8 g++ g++-8 gcc gcc-8 libasan5 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libgcc-8-dev libgomp1 libisl19 libitm1
  liblsan0 libmpc3 libmpfr6 libmpx2 libquadmath0 libstdc++-8-dev libtsan0 libubsan1 linux-libc-dev make
0 upgraded, 29 newly installed, 0 to remove and 1 not upgraded.
Need to get 43.7 MB of archives.
After this operation, 176 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 binutils-common amd64 2.31.1-16 [2,073 kB]
Err:2 http://security.debian.org/debian-security buster/updates/main amd64 linux-libc-dev amd64 4.19.118-2+deb10u1
  404  Not Found [IP: 2a04:4e42:6::644 80]
Get:3 http://deb.debian.org/debian buster/main amd64 libbinutils amd64 2.31.1-16 [478 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 binutils-x86-64-linux-gnu amd64 2.31.1-16 [1,823 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 binutils amd64 2.31.1-16 [56.8 kB]
Get:6 http://deb.debian.org/debian buster/main amd64 libisl19 amd64 0.20-2 [587 kB]
Get:7 http://deb.debian.org/debian buster/main amd64 libmpfr6 amd64 4.0.2-1 [775 kB]
Get:8 http://deb.debian.org/debian buster/main amd64 libmpc3 amd64 1.1.0-1 [41.3 kB]
Get:9 http://deb.debian.org/debian buster/main amd64 cpp-8 amd64 8.3.0-6 [8,914 kB]
Get:10 http://deb.debian.org/debian buster/main amd64 cpp amd64 4:8.3.0-1 [19.4 kB]
Get:11 http://deb.debian.org/debian buster/main amd64 libcc1-0 amd64 8.3.0-6 [46.6 kB]
Get:12 http://deb.debian.org/debian buster/main amd64 libgomp1 amd64 8.3.0-6 [75.8 kB]
Get:13 http://deb.debian.org/debian buster/main amd64 libitm1 amd64 8.3.0-6 [27.7 kB]
Get:14 http://deb.debian.org/debian buster/main amd64 libatomic1 amd64 8.3.0-6 [9,032 B]
Get:15 http://deb.debian.org/debian buster/main amd64 libasan5 amd64 8.3.0-6 [362 kB]
Get:16 http://deb.debian.org/debian buster/main amd64 liblsan0 amd64 8.3.0-6 [131 kB]
Get:17 http://deb.debian.org/debian buster/main amd64 libtsan0 amd64 8.3.0-6 [283 kB]
Get:18 http://deb.debian.org/debian buster/main amd64 libubsan1 amd64 8.3.0-6 [120 kB]
Get:19 http://deb.debian.org/debian buster/main amd64 libmpx2 amd64 8.3.0-6 [11.4 kB]
Get:20 http://deb.debian.org/debian buster/main amd64 libquadmath0 amd64 8.3.0-6 [133 kB]
Get:21 http://deb.debian.org/debian buster/main amd64 libgcc-8-dev amd64 8.3.0-6 [2,298 kB]
Get:22 http://deb.debian.org/debian buster/main amd64 gcc-8 amd64 8.3.0-6 [9,452 kB]
Get:23 http://deb.debian.org/debian buster/main amd64 gcc amd64 4:8.3.0-1 [5,196 B]
Get:24 http://deb.debian.org/debian buster/main amd64 libc-dev-bin amd64 2.28-10 [275 kB]
Get:25 http://deb.debian.org/debian buster/main amd64 libc6-dev amd64 2.28-10 [2,691 kB]
Get:26 http://deb.debian.org/debian buster/main amd64 libstdc++-8-dev amd64 8.3.0-6 [1,532 kB]
Get:27 http://deb.debian.org/debian buster/main amd64 g++-8 amd64 8.3.0-6 [9,752 kB]
Get:28 http://deb.debian.org/debian buster/main amd64 g++ amd64 4:8.3.0-1 [1,644 B]
Get:29 http://deb.debian.org/debian buster/main amd64 make amd64 4.2.1-1.2 [341 kB]
Fetched 42.3 MB in 4s (11.5 MB/s)
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/l/linux/linux-libc-dev_4.19.118-2+deb10u1_amd64.deb  404  Not Found [IP: 2a04:4e42:6::644 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.4' to '10.11'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
Fetched 239 kB in 15s (15.9 kB/s)
Reading package lists... Done
E: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease
E: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease
E: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
gzip is already the newest version (1.9-3).
perl is already the newest version (5.28.1-6).
perl-base is already the newest version (5.28.1-6).
tar is already the newest version (1.30+dfsg-6).
wget is already the newest version (1.20.1-1.1).
ca-certificates is already the newest version (20200601~deb10u1).
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-8 g++-8 gcc-8 libasan5 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libgcc-8-dev libgomp1 libisl19 libitm1 liblsan0
  libmpc3 libmpfr6 libmpx2 libquadmath0 libstdc++-8-dev libtsan0 libubsan1 linux-libc-dev
Suggested packages:
  binutils-doc cpp-doc gcc-8-locales g++-multilib g++-8-multilib gcc-8-doc libstdc++6-8-dbg gcc-multilib manpages-dev autoconf automake libtool flex bison gdb gcc-doc gcc-8-multilib
  libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg libmpx2-dbg libquadmath0-dbg glibc-doc libstdc++-8-doc make-doc
Recommended packages:
  manpages-dev
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-8 g++ g++-8 gcc gcc-8 libasan5 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libgcc-8-dev libgomp1 libisl19 libitm1
  liblsan0 libmpc3 libmpfr6 libmpx2 libquadmath0 libstdc++-8-dev libtsan0 libubsan1 linux-libc-dev make
0 upgraded, 29 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,354 kB/43.7 MB of archives.
After this operation, 176 MB of additional disk space will be used.
Err:1 http://security.debian.org/debian-security buster/updates/main amd64 linux-libc-dev amd64 4.19.118-2+deb10u1
  404  Not Found [IP: 2a04:4e42:6::644 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/l/linux/linux-libc-dev_4.19.118-2+deb10u1_amd64.deb  404  Not Found [IP: 2a04:4e42:6::644 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
依赖安装失败！！
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
按回车键继续或者Ctrl+c退出

**Comment by kirin10000** [comment]
软件源有错误，建议重装系统

**Comment by nvgt610** [comment]
已解决，重新更换软件源。
