### ISSUE TITLE
debian11安装失败，提示php未安装成功

### ISSUE THREAD

**Issue by eastliu** [kirin10000/Xray-script#85]
脚本运行结束时（中途未提示错误），提示去网页登录cloudreve账号进行设置，但是网页打不开，回到终端，按两次回车显示配置信息，但在配置之前有如下提示：
Failed to stop php-fpm.service: Unit php-fpm.service not loaded.
Failed to disable unit: Unit file php-fpm.service does not exist.
此后一段时间，域名也ping不通了，ssh自动断开，过几分钟之后才能重新登陆ssh
系统是debian11 ，oracle的arm机器

**Comment by kirin10000** [comment]
请问你有没有选择安装过php/nextcloud？

**Comment by eastliu** [comment]
我选的是cloudreve，安装过程中并未提示是否需要安装php，这个脚本以前我用过多次，没遇到过这种情况，我也很费解，刚把系统重装成debian10也还是存在同样的问题，不知道问题到底在哪

**Comment by kirin10000** [comment]
有更多的日志吗？我这边无法复现

**Comment by kirin10000** [comment]
> 此后一段时间，域名也ping不通了，ssh自动断开，过几分钟之后才能重新登陆ssh 

从你的描述来看，更像是机器被Ban或者网络不稳定

**Comment by eastliu** [comment]
> > 此后一段时间，域名也ping不通了，ssh自动断开，过几分钟之后才能重新登陆ssh
> 
> 从你的描述来看，更像是机器被Ban或者网络不稳定

我觉得你的判断应该是对的，我出现的问题跟提示的php报错并没什么关系，这个脚本其实已经安装成功了，但是可能触发了某种机制，导致域名短期被ban，但是过一段时间就恢复了，目前我这个机器其他使用正常，打算先不装xray了，取而代之，我安装了v2ray，目前正常
