### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by libea18** [kirin10000/Xray-script#88]
deb http://deb.xanmod.org releases main
gpg: no valid OpenPGP data found.
添加源失败！
开启bbr2失败
如果刚安装完内核，请先重启
如果重启仍然无效，请尝试选项3

i see this error after enter : 
 2. 安装/升级最新xanmod内核并启用bbr  (推荐)
  3. 安装/升级最新xanmod内核并启用bbr2 (推荐)
 ----------------------------------
ubuntu 20.04

**Comment by kirin10000** [comment]
this maybe the problem cause by upstream. I just do what xanmod official site say.

**Comment by shiropro** [comment]
> deb http://deb.xanmod.org releases main gpg: no valid OpenPGP data found. 添加源失败！ 开启bbr2失败 如果刚安装完内核，请先重启 如果重启仍然无效，请尝试选项3
> ## i see this error after enter :
> 2. 安装/升级最新xanmod内核并启用bbr (推荐)
> 3. 安装/升级最新xanmod内核并启用bbr2 (推荐)
> 
> ubuntu 20.04

简单排查，可能原因是 XanMod 的网站用 Cloudflare 做的 CDN，使用的 VPS IP 被 Cloudflare DDoS 防护了，尝试 wget 直接获取 xanmod 的 gpg.key 会返回错误 503

解决办法是希望能有一个手动添加源的选项
