### ISSUE TITLE
centos7下报错依赖安装失败

### ISSUE THREAD

**Issue by PaPerseller** [kirin10000/Xray-script#9]
重装的新系统，选取完协议后报错依赖安装失败，在脚本文本中搜索到相关依赖后手动使用yum安装后才编译nginx成功

**Comment by kirin10000** [comment]
有没有log

**Comment by kirin10000** [comment]
执行这条命令
yum repolist
结果发来我看一下

**Comment by kirin10000** [comment]
已修复

**Comment by PaPerseller** [comment]
> 已修复

感谢修复。顺便报个小问题，板瓦工vps自带centos7不带socat，同时其又不在依赖项中，会导致第一次安装证书失败，建议将socat加入依赖安装中。

**Comment by kirin10000** [comment]
> > 已修复
> 
> 感谢修复。顺便报个小问题，板瓦工vps自带centos7不带socat，同时其又不在依赖项中，会导致第一次安装证书失败，建议将socat加入依赖安装中。

@PaPerseller  本脚本从头到尾不需要安装socat，你看到的那个不是 安装证书失败，只是acme.sh对没有安装socat进行警告而已
