### ISSUE TITLE
acme 证书采用非标准80端口时应该如何处理？

### ISSUE THREAD

**Issue by fseteen** [kirin10000/Xray-script#94]
我在申请ACME证书时遇到一个特殊的应用场景：
运营商可能是封锁了光猫的80端口，因此我需要在路由器上进行端口映射到服务器的80端口，这个映射设置中的允许外部访问的端口在手工申请证书时可以采用 --httpport 参数指定，但我运行 kirin 10000 的 Xray 脚本每次都会提示申请失败，应该是脚本中 acme.sh 指令没有" --httpport "这个可选项，请问这种情况下我应该如何处理？
非常感谢！

**Comment by kirin10000** [comment]
先正常安装，安装过程中提示证书申请失败，按回车键继续。安装完成之后手动将证书放到`/usr/local/nginx/certs`中，文件名分别为域名.cer，域名.key。之后也要自己手动更新证书

**Comment by Zoooooooooo** [comment]
大神，脚本在申请证书这里屡屡失败，是不是因为ZeroSSL的问题？能否教教如何解决，或者更新下脚本？

[Wed Jan  5 07:54:10 UTC 2022] Register account Error: {
  "type": "urn:ietf:params:acme:error:invalidEmail",
  "detail": "Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden",
  "status": 400
}
[Wed Jan  5 07:54:10 UTC 2022] _on_issue_err
[Wed Jan  5 07:54:10 UTC 2022] Please add '--debug' or '--log' to check more details.
[Wed Jan  5 07:54:10 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Wed Jan  5 07:54:10 UTC 2022] Run post hook:'mv /usr/local/nginx/conf/nginx.conf.bak /usr/local/nginx/conf/nginx.conf && sleep 2s && systemctl restart nginx'

**Comment by kirin10000** [comment]
> 大神，脚本在申请证书这里屡屡失败，是不是因为ZeroSSL的问题？能否教教如何解决，或者更新下脚本？
> 
> [Wed Jan 5 07:54:10 UTC 2022] Register account Error: { "type": "urn:ietf:params:acme:error:invalidEmail", "detail": "Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden", "status": 400 } [Wed Jan 5 07:54:10 UTC 2022] _on_issue_err [Wed Jan 5 07:54:10 UTC 2022] Please add '--debug' or '--log' to check more details. [Wed Jan 5 07:54:10 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh [Wed Jan 5 07:54:10 UTC 2022] Run post hook:'mv /usr/local/nginx/conf/nginx.conf.bak /usr/local/nginx/conf/nginx.conf && sleep 2s && systemctl restart nginx'

升级脚本，重置域名

**Comment by cxw620** [comment]
为了安全, 我关掉了除443,9993外的所有端口, 平时通过zerotier连接vps, 也是证书部署失败. 我采用的是这个方法:
freessl.cn提供了免费的Trustaisa dv证书, 它提供了个acme地址自动获取、更新证书. 安装过程中提示证书申请失败后按回车键继续, 完成部署后, 遵照freessl.cn的指引用acme获取证书, 然后部署:
```
acme.sh --install-cert -d example.com \
--key-file       /usr/local/nginx/certs/yourdomain.key \
--fullchain-file /usr/local/nginx/certs/yourdomain.cer \
--reloadcmd     "service nginx force-reload"
```
最后运行安装脚本重启xray和web就行了.
letsencrypt有DNS验证的方式, 作者有意向支持吗?
