### ISSUE TITLE
gprc下的nginx配置错误

### ISSUE THREAD

**Issue by LisPerfect** [kirin10000/Xray-script#97]
配置文件见下方，具体表现为grpc协议下，如打开cf开关。则在访问伪装网页时无限301跳转直到浏览器停止尝试。

**Comment by LisPerfect** [comment]
`root@vultr:/usr/local/etc/xray# cat ./config.json
{
    "log": {
        "loglevel": "none"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "fallbacks": [
                    {
                        "path": "/***",
                        "dest": "@/dev/shm/xray/ws.sock"
                    },
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/nginx_unixsocket/h2.sock"
                    },
                    {
                        "dest": "/dev/shm/nginx_unixsocket/default.sock"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/nginx/certs/***.***.cer",
                            "keyFile": "/usr/local/nginx/certs/***.***.key",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
        },
        {
            "listen": "/dev/shm/xray_unixsocket/grpc.sock",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "**********"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "****"
                }
            }
        },
        {
            "listen": "@/dev/shm/xray/ws.sock",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "************"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/******"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
`

**Comment by LisPerfect** [comment]
```
root@vultr:~# cat /usr/local/nginx/conf.d/xray.conf
server {
    listen 80 reuseport default_server;
    listen [::]:80 reuseport default_server;
    return 301 https://www.***.***;
}
server {
    listen 80;
    listen [::]:80;
    server_name www.***.***;
    return 301 https://$host$request_uri;
}
server {
    listen 80;
    listen [::]:80;
    listen unix:/dev/shm/nginx_unixsocket/default.sock;
    listen unix:/dev/shm/nginx_unixsocket/h2.sock http2;
    server_name ***.***;
    return 301 https://www.$host$request_uri;
}
server {
    listen unix:/dev/shm/nginx_unixsocket/default.sock default_server;
    listen unix:/dev/shm/nginx_unixsocket/h2.sock http2 default_server;
    return 301 https://www.***.***;
}
server {
    listen unix:/dev/shm/nginx_unixsocket/default.sock;
    listen unix:/dev/shm/nginx_unixsocket/h2.sock http2;
    server_name www.***.***;
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
    #client_header_timeout 24h;
    #ignore_invalid_headers off;
    location = /ff76945/TunMulti {
        client_max_body_size 0;
        client_body_timeout 24h;
        #keepalive_requests 1000;
        #keepalive_time 24h;
        keepalive_timeout 24h;
        send_timeout 24h;
        #grpc_buffer_size 0;
        grpc_read_timeout 24h;
        grpc_send_timeout 24h;
        #grpc_socket_keepalive off;
        lingering_close always;
        lingering_time 24h;
        lingering_timeout 24h;
        grpc_pass grpc://unix:/dev/shm/xray_unixsocket/grpc.sock;
    }
    location / {
        proxy_set_header X-Forwarded-For 127.0.0.1;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://unix:/dev/shm/cloudreve_unixsocket/cloudreve.sock;
        client_max_body_size 0;
    }
}
#-----------------不要修改以下内容----------------
#domain_list=www.***.***
#true_domain_list=***.***
#domain_config_list=1
#pretend_list=1

```

**Comment by kirin10000** [comment]
cf下需要设置域名安全为严格，你设置了没有？

**Comment by kirin10000** [comment]
在 tls/https 那边

**Comment by LisPerfect** [comment]
> 在 tls/https 那边

确认cf是严格，并且证书是有效的

**Comment by kirin10000** [comment]
不好意思最近太忙把这事给忘了，，，我看了配置是没有问题的，我这边也无法复现，我不知道什么情况

**Comment by LisPerfect** [comment]
> 不好意思最近太忙把这事给忘了，，，我看了配置是没有问题的，我这边也无法复现，我不知道什么情况

感谢回复，我又新开了一台vps实例，采用同样配置方案尝试复现，但失败了。可我两台vps都是使用的同样的新系统进行配置。我已经把两台vps都快照了，尝试继续研究两台机子的区别。
这个issue我先关了，如果有进一步进展我再来开新issue，thx
