### ISSUE TITLE
Oracle Linux使用脚本更新nginx的时候显示安装epel源失败

### ISSUE THREAD

**Issue by CCCAUCHY** [kirin10000/Xray-script#98]
实际上用 `yum search epel` 得到 `oracle-epel-release-el7.x86_64`

**Comment by kirin10000** [comment]
你先手动安装，然后那一步按回车跳过

**Comment by kirin10000** [comment]
@CCCAUCHY 尝试修复了一下，你试试现在运行有没有问题
