### ISSUE TITLE
关于grpc连接过一段时间后断开连接的问题

### ISSUE THREAD

**Issue by derek1dong** [kirin10000/Xray-script#99]
按照最新的脚本部署了，客户端连接上后，如果没有活动，过一段时间就被服务器主动断开连接了；
现在不清楚怎么定位这个问题；

我看了脚本：
主要参数：       
        client_max_body_size 0;
        client_body_timeout 24h;
        #keepalive_requests 1000;
        #keepalive_time 24h;
        keepalive_timeout 24h;
        send_timeout 24h;
        #grpc_buffer_size 0;
        grpc_read_timeout 24h;
        grpc_send_timeout 24h;
        #grpc_socket_keepalive off;
        lingering_close always;
        lingering_time 24h;
        lingering_timeout 24h;
这些参数应该已经让保活时长为24h了

但是实际情况是android手机后台连接过一段时间，还是会被服务器主动关闭

![image](https://user-images.githubusercontent.com/85718501/148193788-78f87a2a-8fe6-4d60-be8d-00e71994bc92.png)

截图中可以看到，是服务器在16:07:45.478580主动关闭的，
不知道有什么手段能定位这个问题？

xray已经有我自己编译，去掉了go 默认的15秒keepalive

**Comment by kirin10000** [comment]
如果是用cf的话一直都有断连的问题，和脚本无关。最新的1.5.2版本尝试修复了这个问题，需要手动指定`initial_windows_size`参数。

https://github.com/XTLS/Xray-core/releases/tag/v1.5.2

**Comment by derek1dong** [comment]
> 如果是用cf的话一直都有断连的问题，和脚本无关。最新的1.5.2版本尝试修复了这个问题，需要手动指定`initial_windows_size`参数。
> 
> https://github.com/XTLS/Xray-core/releases/tag/v1.5.2

没有使用cf，直连的；
xray前置，h2分流到nginx, 然后nginx再将grpc分流回到xray

**Comment by kirin10000** [comment]
> 没有使用cf，直连的

那就不需要修改服务端配置。

我看到你说安卓客户端，电脑端呢？有可能是客户端的问题

我自己使用没有遇到你说的情况

**Comment by derek1dong** [comment]
> > 没有使用cf，直连的
> 
> 那就不需要修改服务端配置。
> 
> 我看到你说安卓客户端，电脑端呢？有可能是客户端的问题
> 
> 我自己使用没有遇到你说的情况

电脑没问题
v2ray还有歌配置，policy 中的connIdle默认300秒；服务端改了这个之后，好一点；
但是android端，v2raynNG界面没有配置项，看了源代码，这个connIdle还是写死的，得自己编译了

**Comment by kirin10000** [comment]
> 电脑没问题

只要有客户端没有问题就说明不是服务端的问题，不用折腾服务器的配置了
